using System.Numerics;
using Content.Client._Exodus.NPC; // Exodus - faction AI radar label
using Content.Client._Exodus.Territory; // Exodus - territory POI colors
using Content.Client._Mono.Radar;
using Content.Client.Station; // Frontier
using Content.Shared._Crescent.ShipShields;
using Content.Shared._Exodus.NPC.Components; // Exodus - faction AI radar label
using Content.Shared._Mono.Company;
using Content.Shared._Mono.Detection;
using Content.Shared._Mono.Radar;

using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared._Exodus.SpaceArtillery.Components; // Exodus - ShuttleHooks
using Content.Shared._Exodus.BUIStates;
using Content.Shared._Exodus.Shuttles.Components; // Exodus - SafeZone
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Collision.Shapes;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class ShuttleNavControl : BaseShuttleControl // Mono
{
    [Dependency] private IMapManager _mapManager = default!;
    [Dependency] private IUserInterfaceManager _uiManager = default!;
    private readonly DetectionSystem _detection; // Mono
    private readonly StationSystem _station; // Frontier
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform;
    private readonly RadarBlipsSystem _blips;
    private readonly TerritoryPoiColorSystem _territoryPoiColors; // Exodus - territory POI colors
    private readonly IPrototypeManager _prototype; // Exodus - faction AI radar label

    // Exodus - SafeZone - Start
    private EntityQuery<TransformComponent> _xformQuery;
    private EntityQuery<FixturesComponent> _fixturesQuery;
    private EntityQuery<PhysicsComponent> _bodyQuery;
    private EntityQuery<IFFComponent> _IFFQuery;
    private EntityQuery<MapGridComponent> _gridQuery;
    private EntityQuery<MetaDataComponent> _metaDataQuery;
    private EntityQuery<CompanyComponent> _companyQuery;
    private EntityQuery<FactionAiControlledGridComponent> _factionAiControlQuery; // Exodus - faction AI radar label
    private EntityQuery<ZoneComponent> _zoneQuery;
    // Exodus - SafeZone - End

    /// <summary>
    /// Used to transform all of the radar objects. Typically is a shuttle console parented to a grid.
    /// </summary>
    protected EntityCoordinates? _coordinates; // Mono

    /// <summary>
    /// Entity of controlling console
    /// </summary>
    protected EntityUid? _consoleEntity; // Mono

    // Mono - is world rotation of the view.
    protected Angle? _rotation = Angle.Zero;

    private Dictionary<NetEntity, List<DockingPortState>> _docks = new();

    // temporary buffers to avoid per-frame heap churn
    private readonly List<BlipData> _tempBlipDataList = new();
    private readonly HashSet<EntityUid> _visibleGridsSet = new();
    // Exodus-begin nebula-radar-visualization
    private const float NebulaFillAlpha = 0.08f;
    private Vector2[] _nebulaFillBuffer = [];
    private Vector2[] _nebulaLineBuffer = [];
    // Exodus-end

    // Exodus-begin mass-scanner-perf
    private Vector2[] _radarPosVerts = new Vector2[RadarPosVertsCache.Length];
    private Vector2[] _shapeDrawBuffer = new Vector2[97];
    // Exodus-end

    // Exodus-begin territory-marker
    /// <summary>
    /// World-space repeat distance (in meters) for the diagonal repeated faction label pattern inside territory rings.
    /// The screen step is computed as TerritoryTextWorldRepeat * MinimapScale and the pattern is always centered on the ring.
    /// This makes the text pattern fully static relative to the ring geometry, without movement or phase shift on pan or any zoom.
    /// Increase to make sparser, decrease for denser fill.
    /// </summary>
    private const float TerritoryTextWorldRepeat = 1800f;
    private const float TerritoryTextFadeInDiagMultiplier = 3f;
    private const float TerritoryTextFullDiagMultiplier = 7f;
    private const float TerritoryTextFadeOutViewDiagMultiplier = 0.9f;
    private const float TerritoryTextHiddenViewDiagMultiplier = 1.35f;
    private readonly Dictionary<string, string> _territoryLabelCache = new(); // Exodus mass-scanner-perf
    // Exodus-end
    // Exodus-begin dock-label-fade
    private const float DockLabelFadeOutWorldRange = 250f;
    private const float DockLabelHiddenWorldRange = 750f;
    // Exodus-end
    private static readonly Vector2[] RadarPosVertsCache =
    [
        new Vector2(0f, -2f),
        new Vector2(1f, 0f),
        new Vector2(0f, 2f),
        new Vector2(-1f, 0f),
    ];

    public bool ShowIFF { get; set; } = true;
    public bool ShowIFFShuttles { get; set; } = true;
    public bool ShowDocks { get; set; } = true;

    public float MaximumIFFDistance { get; set; } = 3000f; // Frontier // Mono - 3000 by default to not gigaclutter
    public bool HideCoords { get; set; } = false; // Frontier

    private static Color _dockLabelColor = Color.White; // Frontier

    /// <summary>
    ///   If present, called for every IFF. Must determine if it should or should not be shown.
    /// </summary>
    public Func<EntityUid, MapGridComponent, IFFComponent?, bool, string, bool>? IFFFilter { get; set; } = null;

    /// <summary>
    /// Raised if the user left-clicks on the radar control with the relevant entitycoordinates.
    /// </summary>
    public Action<EntityCoordinates>? OnRadarClick;

    private List<Entity<MapGridComponent>> _grids = new();

    // Mono - set if we want this to detect not from itself
    public List<EntityUid>? Detectors = null;

    #region Mono
    // These 2 handle timing updates
    protected const float RadarUpdateInterval = 0f;
    protected float _updateAccumulator = 0f;

    // doesn't support absolute panning and angle follow, but why would you need that?
    protected bool _relativePanning = false;
    protected bool _angleFollow = true;
    private bool _radarModeDefaultsApplied;

    private bool _wasPanned = false;
    #endregion

    protected bool _isMouseDown;
    protected bool _isMouseInside;
    protected Vector2 _lastMousePos;
    protected float _lastFireTime;
    protected const float FireRateLimit = 0.1f; // 100ms between shots

    private List<GrapplingLinkState> _grapLinks = new(); // Exodus - ShuttleHooks

    private enum RadarAzimuthMode : byte
    {
        Edge,
        Ring,
        Off,
    }

    private BoxContainer? _radarModeButtons;
    private RadarModeButton? _radarAzimuthButton;
    private RadarModeButton? _radarRotationButton;
    private RadarModeButton? _radarAnchorButton;
    private RadarModeButton? _radarResetButton;
    private RadarAzimuthMode _azimuthMode;

    public ShuttleNavControl() : this(64f, 256f, 256f) { } // Mono

    public ShuttleNavControl(float minRange, float maxRange, float range) : base(minRange, maxRange, range) // Mono
    {
        RobustXamlLoader.Load(this);
        _detection = EntManager.System<DetectionSystem>(); // Mono
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
        _station = EntManager.System<StationSystem>(); // Frontier
        _blips = EntManager.System<RadarBlipsSystem>();
        _territoryPoiColors = EntManager.System<TerritoryPoiColorSystem>(); // Exodus - territory POI colors
        _prototype = IoCManager.Resolve<IPrototypeManager>(); // Exodus - faction AI radar label

        // Exodus - SafeZone - Start
        _xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        _fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        _bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();
        _IFFQuery = EntManager.GetEntityQuery<IFFComponent>();
        _gridQuery = EntManager.GetEntityQuery<MapGridComponent>();
        _metaDataQuery = EntManager.GetEntityQuery<MetaDataComponent>();
        _companyQuery = EntManager.GetEntityQuery<CompanyComponent>();
        _factionAiControlQuery = EntManager.GetEntityQuery<FactionAiControlledGridComponent>(); // Exodus - faction AI radar label
        _zoneQuery = EntManager.GetEntityQuery<ZoneComponent>();
        // Exodus - SafeZone - End

        OnMouseEntered += HandleMouseEntered;
        OnMouseExited += HandleMouseExited;
    }

    private void HandleMouseEntered(GUIMouseHoverEventArgs args)
    {
        _isMouseInside = true;
    }

    private void HandleMouseExited(GUIMouseHoverEventArgs args)
    {
        _isMouseInside = false;
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        if (_wasPanned) // Mono hack
            return;

        _coordinates = coordinates;
        // Mono - TODO: either remove this or make this do anything
        // _rotation = angle;
    }

    public void SetConsole(EntityUid? consoleEntity)
    {
        if (_consoleEntity == consoleEntity)
            return;

        _consoleEntity = consoleEntity;
        _radarModeDefaultsApplied = false;
        ApplyRadarModeDefaults();
    }

    // converts Offset to world-relative offset so we can modify radar parameters without conversion headaches
    // call this before potentially rotation-modifying operations and PanToEnt() after
    private void PanToWorld()
    {
        if (!_angleFollow || _coordinates is not { } cord)
            return;
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        Offset = coordEntRot.RotateVec(Offset);
    }

    // converts world-relative Offset to relative to current view
    // call this after potentially rotation-modifying operations and PanToWorld() before
    private void PanToEnt()
    {
        if (!_angleFollow || _coordinates is not { } cord)
            return;
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        Offset = (-coordEntRot).RotateVec(Offset);
    }

    // reanchor our view to console or grid
    private void ReanchorView()
    {
        if (_consoleEntity is not { } cons
        || _coordinates is not { } cord
        || !EntManager.TryGetComponent<TransformComponent>(cons, out var xform))
            return;

        PanToWorld();
        var anchTo = cons;
        if (xform.GridUid != null)
            anchTo = xform.GridUid.Value;
        _coordinates = _transform.WithEntityId(cord, anchTo);
        _relativePanning = true;
        PanToEnt();
    }

    private void EnsureRadarModeButtons()
    {
        if (_radarModeButtons != null)
            return;

        if (Parent is not LayoutContainer parent)
            return;

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        _radarModeButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            HorizontalExpand = false,
            VerticalExpand = false,
            MouseFilter = MouseFilterMode.Stop,
        };

        _radarAzimuthButton = CreateRadarModeButton(RadarModeButtonIcon.Azimuth);
        _radarAzimuthButton.ToolTip = Loc.GetString("shuttle-console-button-azimuth");
        _radarAzimuthButton.OnPressed += _ =>
        {
            _azimuthMode = _azimuthMode switch
            {
                RadarAzimuthMode.Edge => RadarAzimuthMode.Ring,
                RadarAzimuthMode.Ring => RadarAzimuthMode.Off,
                _ => RadarAzimuthMode.Edge,
            };
        };

        _radarRotationButton = CreateRadarModeButton(RadarModeButtonIcon.Rotation);
        _radarRotationButton.ToolTip = Loc.GetString("shuttle-console-button-rotation");
        _radarRotationButton.OnPressed += _ =>
        {
            PanToWorld();
            _angleFollow ^= true;
            PanToEnt();
        };

        _radarAnchorButton = CreateRadarModeButton(RadarModeButtonIcon.Anchor);
        _radarAnchorButton.ToolTip = Loc.GetString("shuttle-console-button-anchor");
        _radarAnchorButton.OnPressed += _ =>
        {
            if (_coordinates is not { } cord)
                return;

            // if we're anchored or not yet bound to map, just deanchor
            if (_relativePanning || !EntManager.HasComponent<MapComponent>(cord.EntityId))
            {
                PanToWorld();
                // we're deanchoring, so simply detach our view to the map
                _coordinates = _transform.ToCoordinates(_transform.ToMapCoordinates(cord));
                _relativePanning = false;
                _wasPanned = true;
                PanToEnt();
            }
            else
            {
                ReanchorView();
            }
        };

        _radarResetButton = CreateRadarModeButton(RadarModeButtonIcon.Reset);
        _radarResetButton.ToolTip = Loc.GetString("shuttle-console-button-reset");
        _radarResetButton.OnPressed += _ =>
        {
            _radarModeDefaultsApplied = false;
            ApplyRadarModeDefaults();
            if (EntManager.TryGetComponent<TransformComponent>(_consoleEntity, out var xform))
            {
                Offset = Vector2.Zero;
                _coordinates = xform.Coordinates;
                ReanchorView();
            }
        };

        _radarModeButtons.AddChild(_radarAzimuthButton);
        _radarModeButtons.AddChild(_radarRotationButton);
        _radarModeButtons.AddChild(_radarAnchorButton);
        _radarModeButtons.AddChild(_radarResetButton);

        parent.AddChild(_radarModeButtons);
        LayoutContainer.SetAnchorAndMarginPreset(_radarModeButtons, LayoutContainer.LayoutPreset.BottomLeft, margin: 10);
    }

    private void ApplyRadarModeDefaults()
    {
        if (_radarModeDefaultsApplied)
            return;

        if (!EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
            return;

        _radarModeDefaultsApplied = true;
        Draggable = radar.Pannable;
        _angleFollow = !radar.NoRotate;
        _relativePanning = radar.RelativePanning;
    }

    private static RadarModeButton CreateRadarModeButton(RadarModeButtonIcon icon = RadarModeButtonIcon.None)
    {
        return new RadarModeButton(icon)
        {
            MinWidth = 16f,
            MaxWidth = 16f,
            MinHeight = 16f,
            MaxHeight = 16f,
            HorizontalExpand = false,
            VerticalExpand = false,
            ModulateSelfOverride = Color.White.WithAlpha(0.55f),
        };
    }

    internal enum RadarModeButtonIcon : byte
    {
        None,
        Azimuth,
        Rotation,
        Anchor,
        Reset
    }

    public sealed class RadarModeButton : BaseButton
    {
        private readonly RadarModeButtonIcon _icon;

        internal RadarModeButton(RadarModeButtonIcon icon)
        {
            _icon = icon;
        }

        protected override Vector2 MeasureOverride(Vector2 availableSize)
        {
            return new Vector2(16f, 16f);
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            var alpha = DrawMode switch
            {
                DrawModeEnum.Pressed => 0.62f,
                DrawModeEnum.Hover => 0.48f,
                _ => 0.32f,
            };

            var center = new Vector2(PixelSize.X * 0.5f, PixelSize.Y * 0.5f);
            var radius = MathF.Min(PixelSize.X, PixelSize.Y) * 0.42f;
            handle.DrawCircle(center, radius, Color.White.WithAlpha(alpha));

            var up = new Vector2(0f, -radius);
            var down = new Vector2(0f, radius);
            var leftOffs = new Vector2(-radius, 0f);
            var rightOffs = new Vector2(radius, 0f);
            var top = center + up;
            var bottom = center + down;
            var left = center + leftOffs;
            var right = center + rightOffs;

            switch (_icon) {
                case RadarModeButtonIcon.Azimuth:
                {
                    var iconColor = Color.Black.WithAlpha(0.95f);
                    var topLeft = center + (up + leftOffs) / MathF.Sqrt(2f);
                    var topRight = center + (up + rightOffs) / MathF.Sqrt(2f);
                    var bottomLeft = center + (down + leftOffs) / MathF.Sqrt(2f);
                    var bottomRight = center + (down + rightOffs) / MathF.Sqrt(2f);

                    handle.DrawLine(topLeft, bottomRight, iconColor);
                    handle.DrawLine(bottomLeft, topRight, iconColor);
                    handle.DrawLine(left, right, iconColor);
                    handle.DrawLine(bottom, top, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Rotation:
                {
                    var iconColor = Color.Yellow.WithAlpha(0.95f);
                    var innerRatio = 0.8f;
                    var segCount = 3;
                    var prevOffs = up * innerRatio;
                    for (var i = 0; i < segCount; i++)
                    {
                        var angle = Angle.FromDegrees(120f * i / (float)segCount - 15f);
                        var thisOffs = angle.RotateVec(up * innerRatio);
                        var thisPointUp = center + thisOffs;
                        var thisPointDown = center - thisOffs;
                        var oldPointUp = center + prevOffs;
                        var oldPointDown = center - prevOffs;
                        handle.DrawLine(oldPointUp, thisPointUp, iconColor);
                        handle.DrawLine(oldPointDown, thisPointDown, iconColor);
                        prevOffs = thisOffs;
                    }
                    break;
                }
                case RadarModeButtonIcon.Anchor:
                {
                    var iconColor = Color.Blue.WithAlpha(0.95f);
                    var stemTop = center + up * 0.5f;
                    var crossLeft = center + leftOffs * 0.3f + up * 0.7f;
                    var crossRight = center + rightOffs * 0.3f + up * 0.7f;;
                    var leftFluke = center + leftOffs * 0.6f + down * 0.6f;
                    var rightFluke = center + rightOffs * 0.6f + down * 0.6f;
                    var innerRadius = radius * 0.4f;
                    var innerTop = center + up * 0.6f;

                    handle.DrawCircle(innerTop, innerRadius, iconColor, false);
                    handle.DrawLine(stemTop, bottom, iconColor);
                    handle.DrawLine(crossLeft, crossRight, iconColor);
                    handle.DrawLine(bottom, leftFluke, iconColor);
                    handle.DrawLine(bottom, rightFluke, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Reset:
                {
                    var iconColor = Color.Red.WithAlpha(0.95f);
                    handle.DrawLine(left, right, iconColor);
                    break;
                }
                default:
                    break;
            }
        }
    }

    // Mono - evil hack
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        if (_isMouseInside)
            _lastMousePos = args.RelativePosition;

        if (!_draggin || _coordinates == null)
            return;

        if (!_relativePanning
            && _coordinates?.EntityId is { } coordEnt
            && EntManager.TryGetComponent<TransformComponent>(coordEnt, out var coordXform)
            && coordXform.MapUid != coordEnt
        )
            _coordinates = _transform.ToCoordinates(_transform.ToMapCoordinates(_coordinates.Value));


        _wasPanned = true;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = true;
        _lastMousePos = args.RelativePosition;
        TryFireAtPosition(args.RelativePosition);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = false;

        var coords = GetMouseEntityCoordinates(args.RelativePosition);
        OnRadarClick?.Invoke(coords);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateAccumulator += args.DeltaSeconds;

        if (_updateAccumulator >= RadarUpdateInterval)
        {
            _updateAccumulator = 0; // I'm not subtracting because frame updates can majorly lag in a way normal ones cannot.

            if (_consoleEntity != null)
                _blips.RequestBlips((EntityUid)_consoleEntity);
        }

        if (_isMouseDown && _isMouseInside)
        {
            var currentTime = IoCManager.Resolve<IGameTiming>().CurTime.TotalSeconds;
            if (currentTime - _lastFireTime >= FireRateLimit)
            {
                var mousePos = UserInterfaceManager.MousePositionScaled;
                var relativePos = mousePos.Position - GlobalPosition;
                if (relativePos != _lastMousePos)
                {
                    _lastMousePos = relativePos;
                }
                TryFireAtPosition(relativePos);
                _lastFireTime = (float)currentTime;
            }
        }
    }

    private void TryFireAtPosition(Vector2 relativePosition)
    {
        var coords = GetMouseEntityCoordinates(relativePosition);
        OnRadarClick?.Invoke(coords);
    }

    /// <summary>
    /// Gets the entity coordinates of where the mouse position is, relative to the control.
    /// </summary>
    [PublicAPI]
    public EntityCoordinates GetMouseCoordinatesFromCenter()
    {
        if (_coordinates == null || _rotation == null)
        {
            return EntityCoordinates.Invalid;
        }

        var pos = _uiManager.MousePositionScaled.Position - GlobalPosition;
        return GetMouseEntityCoordinates(pos);
    }

    public void UpdateState(NavInterfaceState state)
    {
        EnsureRadarModeButtons();
        ApplyRadarModeDefaults();
        SetMatrix(EntManager.GetCoordinates(state.Coordinates), state.Angle);

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
        {
            ActualRadarRange = WorldMaxRange;
        }

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);

        // Frontier
        if (state.MaxIffRange != null)
            MaximumIFFDistance = state.MaxIffRange.Value;
        HideCoords = state.HideCoords;
        // End Frontier

        _docks = state.Docks;

        _grapLinks = state.GrapLinks; // Exodus - ShuttleHooks

        NfUpdateState(state); // Frontier Update State
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);
        DrawCircles(handle);

        // No data
        if (_coordinates == null || _rotation == null)
        {
            return;
        }

        if (!_xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform) // Exodus - SafeZone
            || xform.MapID == MapId.Nullspace)
        {
            return;
        }

        // Mono
        if (EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
        {
            Draggable = radar.Pannable;
        }
        // Mono - TODO: remove _rotation and make it a method instead
        var coordEnt = _coordinates.Value.EntityId;
        var coordEntRot = _transform.GetWorldRotation(coordEnt);
        if (_angleFollow && EntManager.TryGetComponent<TransformComponent>(coordEnt, out var coordXform))
            _rotation = coordEntRot;
        else
            _rotation = Angle.Zero;

        var worldRot = _rotation.Value;
        var mapPos = _transform.ToMapCoordinates(_coordinates.Value).Offset(_rotation.Value.RotateVec(Offset));
        var mapCoord = _transform.ToCoordinates(mapPos);
        var worldToShuttle = Matrix3Helpers.CreateTranslation(-mapCoord.Position) * Matrix3Helpers.CreateRotation(-worldRot);
        Matrix3x2.Invert(worldToShuttle, out var shuttleToWorld);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);
        var worldToView = worldToShuttle * shuttleToView;

        // Draw shields
        DrawShields(handle, xform, worldToShuttle);

        // Frontier Corvax: north line drawing
        DrawNorthLine(handle, worldRot);

        // Mono
        switch (_azimuthMode)
        {
            case RadarAzimuthMode.Edge:
                DrawAzimuthScale(handle, worldRot);
                break;
            case RadarAzimuthMode.Ring:
                DrawAzimuthRing(handle, worldRot);
                break;
        }

        if (worldRot != Angle.Zero)
        {
            DrawCompassOverlay(handle, coordEntRot);
        }

        // Draw our grid in detail
        var ourGridId = xform.GridUid;

        if (_gridQuery.TryGetComponent(ourGridId, out var ourGrid) && ourGridId != null &&
            _fixturesQuery.HasComponent(ourGridId.Value)) // Exodus - SafeZone
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            DrawGrid(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
            DrawDocks(handle, ourGridId.Value, ourGridToView);
        }

        // Draw radar position on the station
        // Exodus mass-scanner-perf: reuse verts buffer instead of allocating each frame.
        for (var i = 0; i < _radarPosVerts.Length; i++)
        {
            _radarPosVerts[i] = ScalePosition(RadarPosVertsCache[i]);
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, _radarPosVerts, Color.Lime);

        var viewBounds = new Box2Rotated(new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position), worldRot, mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _grids, approx: true, includeMap: false);

        // Mono edited: Frontier - collect blip location data outside foreach - more changes ahead
        _tempBlipDataList.Clear();

        _visibleGridsSet.Clear();

        // Draw other grids... differently
        foreach (var grid in _grids)
        {
            var gUid = grid.Owner;
            if (gUid == ourGridId || !_fixturesQuery.HasComponent(gUid)) // Exodus - SafeZone
                continue;

            var gridBody = _bodyQuery.GetComponent(gUid); // Exodus - SafeZone
            _IFFQuery.TryGetComponent(gUid, out var iff); // Exodus - SafeZone

            if (!_shuttles.CanDraw(gUid, gridBody, iff))
                continue;

            var hideLabel = iff != null && (iff.Flags & IFFFlags.HideLabel) != 0x0;
            var noLabel = iff != null && (iff.Flags & IFFFlags.HideLabelAlways) != 0x0;
            var detectionLevel = _consoleEntity == null ? DetectionLevel.Detected : GetGridDetected(grid.Owner);
            var detected = detectionLevel != DetectionLevel.Undetected || !hideLabel;
            var blipOnly = detectionLevel != DetectionLevel.Detected; // don't show outline outside of detection radius even if IFF on
            if (!detected)
                continue;

            if (!blipOnly)
                _visibleGridsSet.Add(grid);
            var curGridToWorld = _transform.GetWorldMatrix(gUid);
            var curGridToView = curGridToWorld * worldToView;

            var hideColor = hideLabel && iff != null && (iff.Flags & IFFFlags.AlwaysShowColor) == 0x0;
            var labelColor = hideColor ? blipOnly ? Color.Orange : Color.White : _shuttles.GetIFFColor(grid, self: false, iff);
            if (!hideColor && _territoryPoiColors.TryGetColor(gUid, out var territoryPoiColor))
                labelColor = territoryPoiColor; // Exodus - territory POI colors

            var coordColor = new Color(labelColor.R * 0.8f, labelColor.G * 0.8f, labelColor.B * 0.8f, 0.5f);

            var isPlayerShuttle = iff != null && (iff.Flags & IFFFlags.IsPlayerShuttle) != 0x0;
            // Others default:
            // Color.FromHex("#FFC000FF")
            // Hostile default: Color.Firebrick
            // Mono
            var labelName = noLabel ? null : hideLabel ?
                detectionLevel == DetectionLevel.PartialDetected ?
                    Loc.GetString($"shuttle-console-signature-infrared")
                    : _detection.HandleUnknownMassLabel(grid.Owner)
                : _shuttles.GetIFFLabel(grid, self: false, component: iff);

            var shouldDrawIFF = ShowIFF && labelName != null;
            if (shouldDrawIFF)
            {
                if (IFFFilter != null)
                    shouldDrawIFF &= IFFFilter(gUid, grid.Comp, iff, hideLabel, labelName!);
                if (isPlayerShuttle)
                    shouldDrawIFF &= ShowIFFShuttles;
            }

            //var mapCenter = curGridToWorld. * gridBody.LocalCenter;
            //shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapCenter, curGridToWorld); // Frontier code
            // Frontier: range checks // Mono
            var gridMapPos = _transform.ToMapCoordinates(new EntityCoordinates(gUid, gridBody.LocalCenter)).Position;
            if (!hideLabel) // Mono - show thermal signatures even at long range
                shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapPos.Position - gridMapPos);
            // End Frontier

            // Mono
            var gridUiPosition = Vector2.Transform(gridBody.LocalCenter, curGridToView) / UIScale;

            if (shouldDrawIFF)
            {
                //var gridCentre = Vector2.Transform(gridBody.LocalCenter, curGridToView);
                //gridCentre.Y = -gridCentre.Y;

                // Frontier: IFF drawing functions
                // The actual position in the UI. We offset the matrix position to render it off by half its width
                // plus by the offset.
                //var uiPosition = ScalePosition(gridCentre) / UIScale;
                var uiPosition = gridUiPosition; // Mono

                // Confines the UI position within the viewport.
                var uiXCentre = (int)Width / 2;
                var uiYCentre = (int)Height / 2;
                var uiXOffset = uiPosition.X - uiXCentre;
                var uiYOffset = uiPosition.Y - uiYCentre;
                var uiDistance = (int)Math.Sqrt(Math.Pow(uiXOffset, 2) + Math.Pow(uiYOffset, 2));
                if (uiDistance == 0)
                    uiDistance = 1;
                var uiX = uiXCentre * uiXOffset / uiDistance;
                var uiY = uiYCentre * uiYOffset / uiDistance;

                var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
                if (isOutsideRadarCircle)
                {
                    // 0.95f for offsetting the icons slightly away from edge of radar so it doesnt clip.
                    uiX = uiXCentre * uiXOffset / uiDistance * 0.95f;
                    uiY = uiYCentre * uiYOffset / uiDistance * 0.95f;
                    uiPosition = new Vector2(
                        x: uiX + uiXCentre,
                        y: uiY + uiYCentre
                    );
                }

                var scaledMousePosition = GetMouseCoordinatesFromCenter().Position * UIScale;
                var isMouseOver = Vector2.Distance(scaledMousePosition, uiPosition * UIScale) < 30f;

                // Distant stations that are not player controlled ships
                var isDistantPOI = iff != null || (iff == null || (iff.Flags & IFFFlags.IsPlayerShuttle) == 0x0);

                var distance = Vector2.Distance(gridMapPos, mapPos.Position);

                if (!isOutsideRadarCircle || isDistantPOI || isMouseOver)
                {
                    // Shows decimal when distance is < 50m, otherwise pointless to show it.
                    var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";
                    var labelText = Loc.GetString("shuttle-console-iff-label", ("name", labelName)!, ("distance", displayedDistance));
                    if (!hideLabel) // Exodus - faction AI radar label
                        labelText = AddFactionAiControlLabel(gUid, labelText); // Exodus - faction AI radar label

                    var coordsText = $"({gridMapPos.X:0.0}, {gridMapPos.Y:0.0})";

                    #region Mono

                    // Why are the magic numbers 0.9 and 0.7 used? I have no fucking clue.
                    var labelDimensions = GetMultilineLabelDimensions(handle, labelText.AsSpan(), 0.9f); // Exodus - faction AI radar label
                    var blipSize = RadarBlipSize * 0.7f;

                    // The center of the radar in UI space.
                    var uiCenter = new Vector2(Width * 0.5f, Height * 0.5f);

                    // Whether the blip is on the left side of the center of the radar.
                    var isOnLeftSide = (uiPosition - uiCenter).X < 0;

                    // The UI position of the bottom-left corner of the label, relative to the UI center of the radar, when the label is right-aligned.
                    var labelPosition = uiPosition + new Vector2(-labelDimensions.X - blipSize, -labelDimensions.Y * 0.5f) - uiCenter;

                    // The bounds corners of the label, relative to labelPosition.
                    // The radius and squared radius of the radar, in virtual pixels.
                    var radius = Width * 0.5f;
                    var squaredRadius = radius * radius;

                    // If true, flip the entire label to the right side of the blip and left-align it.
                    // We default to the label being on the left side of the blip because it looked better to me in testing. (arbitrary)
                    var flipLabel = isOnLeftSide && LabelExtendsBeyondRadar(labelPosition, labelDimensions, squaredRadius); // Exodus mass-scanner-perf

                    // Calculate unscaled offsets.
                    var labelOffset = new Vector2()
                    {
                        X = flipLabel
                            ? blipSize // Label on the right side of the blip, left-aligned text.
                            : -labelDimensions.X - blipSize, // Label on the left side of the blip, right-aligned text.
                        Y = -labelDimensions.Y * 0.5f
                    };

                    #endregion Mono

                    // Get company color if entity has CompanyComponent
                    var displayColor = labelColor;
                    if (!hideLabel && _companyQuery.TryGetComponent(gUid, out CompanyComponent? companyComp) && // Exodus - SafeZone
                        !string.IsNullOrEmpty(companyComp.CompanyName))
                    {
                        CompanyPrototype? prototype = null;
                        if (_prototype.TryIndex(companyComp.CompanyName, out prototype) && prototype != null)
                        {
                            displayColor = prototype.Color;
                        }
                    }

                    DrawMultilineLabel(handle, uiPosition, labelOffset, labelText.AsSpan(), UIScale * 0.9f, displayColor); // Exodus - faction AI radar label

                    if (isMouseOver && !HideCoords)
                    {
                        var coordDimensions = handle.GetDimensions(Font, coordsText, 0.7f);
                        var coordOffset = new Vector2()
                        {
                            X = uiPosition.X > Width / 2f
                                ? -coordDimensions.X - blipSize / 0.7f // right align the text to left of the blip (0.7 needed for scale)
                                : blipSize, // left align the text to the right of the blip
                            Y = labelOffset.Y + labelDimensions.Y + 5 // Exodus - faction AI radar label
                        };
                        handle.DrawString(Font, (uiPosition + coordOffset) * UIScale, coordsText, 0.7f * UIScale, displayColor);
                    }
                }

                NfAddBlipToList(_tempBlipDataList, isOutsideRadarCircle, uiPosition, uiXCentre, uiYCentre, labelColor, hideLabel ? default : gUid); // Frontier code
                // End Frontier: IFF drawing functions
            }

            // Detailed view
            var gridAABB = curGridToWorld.TransformBox(grid.Comp.LocalAABB);

            // Skip drawing if it's out of range.
            if (!gridAABB.Intersects(viewAABB))
                continue;

            // Mono
            if (!blipOnly)
            {
                DrawGrid(handle, curGridToView, grid, labelColor);
                DrawDocks(handle, gUid, curGridToView);
            }
        }

        // Frontier: draw target
        if (!HideTarget && Target is { } target)
        {
            var targetEntity = EntManager.GetEntity(TargetEntity);

            string targetName;
            if (targetEntity != EntityUid.Invalid && _metaDataQuery.TryGetComponent(targetEntity, out var targetMeta)) // Exodus - SafeZone
                targetName = targetMeta.EntityName;
            else
                targetName = Loc.GetString("shuttle-console-target-name");

            var curGridToView = Matrix3Helpers.CreateTranslation(target) * worldToShuttle * shuttleToView;

            var labelColor = Color.FromHex("#99ff66");
            var coordColor = new Color(labelColor.R * 0.8f, labelColor.G * 0.8f, labelColor.B * 0.8f, 0.5f);

            var uiPosition = Vector2.Transform(Vector2.Zero, curGridToView) / UIScale;

            var uiXCentre = (int) Width / 2;
            var uiYCentre = (int) Height / 2;
            var uiXOffset = uiPosition.X - uiXCentre;
            var uiYOffset = uiPosition.Y - uiYCentre;
            var uiDistance = (int) Math.Sqrt(Math.Pow(uiXOffset, 2) + Math.Pow(uiYOffset, 2));
            if (uiDistance == 0)
                uiDistance = 1;
            var uiX = uiXCentre * uiXOffset / uiDistance;
            var uiY = uiYCentre * uiYOffset / uiDistance;

            var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
            if (isOutsideRadarCircle)
            {
                uiX = uiXCentre * uiXOffset / uiDistance * 0.95f;
                uiY = uiYCentre * uiYOffset / uiDistance * 0.95f;
                uiPosition = new Vector2(
                    x: uiX + uiXCentre,
                    y: uiY + uiYCentre
                );
            }

            var scaledMousePosition = GetMouseCoordinatesFromCenter().Position * UIScale;
            var isMouseOver = Vector2.Distance(scaledMousePosition, uiPosition * UIScale) < 30f;

            var distance = Vector2.Distance(target, mapPos.Position);
            var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";
            var labelText = Loc.GetString("shuttle-console-iff-label", ("name", targetName)!, ("distance", displayedDistance));

            var coordsText = $"({target.X:0.0}, {target.Y:0.0})";

            var labelDimensions = handle.GetDimensions(Font, labelText, 0.9f);
            var blipSize = RadarBlipSize * 0.7f;
            var labelOffset = new Vector2()
            {
                X = uiPosition.X > Width / 2f
                    ? -labelDimensions.X - blipSize
                    : blipSize,
                Y = -labelDimensions.Y / 2f
            };

            handle.DrawString(Font, (uiPosition + labelOffset) * UIScale, labelText, UIScale * 0.9f, labelColor);
            if (isMouseOver && !HideCoords)
            {
                var coordDimensions = handle.GetDimensions(Font, coordsText, 0.7f);
                var coordOffset = new Vector2()
                {
                    X = uiPosition.X > Width / 2f
                        ? -coordDimensions.X - blipSize / 0.7f
                        : blipSize,
                    Y = coordDimensions.Y / 2
                };
                handle.DrawString(Font, (uiPosition + coordOffset) * UIScale, coordsText, 0.7f * UIScale, coordColor);
            }

            NfAddBlipToList(_tempBlipDataList, isOutsideRadarCircle, uiPosition, uiXCentre, uiYCentre, labelColor); // Frontier code
        }

        // Draw all blips on the map at this point.
        NfDrawBlips(handle, _tempBlipDataList);
        // End Frontier: draw target

        // If we've set the controlling console, and it's on a different grid
        // to the shuttle itself, then draw an additional marker to help the
        // player determine where they are relative to the shuttle.
        if (_consoleEntity != null && _xformQuery.TryGetComponent(_consoleEntity, out var consoleXform)) // Exodus - SafeZone
        {
            if (consoleXform.ParentUid != _coordinates.Value.EntityId)
            {
                var consolePositionWorld = _transform.GetWorldPosition((EntityUid)_consoleEntity);
                var p = Vector2.Transform(consolePositionWorld, worldToView);
                handle.DrawCircle(p, 5, Color.ToSrgb(Color.Cyan), true);
            }
        }

        #region Mono
        // Draw radar line
        // First, figure out which angle to draw.
        var updateRatio = _updateAccumulator / RadarUpdateInterval;

        Angle angle = updateRatio * Math.Tau;
        var origin = ScalePosition(-new Vector2(Offset.X, -Offset.Y));
        handle.DrawLine(origin, origin + angle.ToVec() * ScaledMinimapRadius * 1.42f, Color.Red.WithAlpha(0.1f));

        // Get blips
        var rawBlips = _blips.GetCurrentBlips();

        // Prepare view bounds for culling
        var monoViewBounds = new Box2(-3f, -3f, PixelSize.X + 3f, PixelSize.Y + 3f);

        // Draw blips using the same grid-relative transformation approach as docks
        foreach (var blip in rawBlips)
        {
            // Exodus-begin territory-marker
            if (blip.Config.Shape == RadarBlipShape.TerritoryCircle)
                continue;
            // Exodus-end

            var position = Vector2.Transform(_transform.ToMapCoordinates(blip.Position).Position, worldToView);
            var color = blip.Config.Color.WithAlpha(0.8f);
            var box = new Box2Rotated(blip.Config.Bounds, 0);
            if (blip.Config.RespectZoom)
                box.Box = new Box2(box.Box.BottomLeft * MinimapScale, box.Box.TopRight * MinimapScale);
            if (blip.Config.Rotate)
                box.Rotation = worldRot - blip.Rotation;

            if (blip.GridUid is { } grid)
            {
                // check detection if we're on a grid and that grid isn't our grid
                if (!_visibleGridsSet.Contains(grid) && grid != ourGridId)
                    continue;
            }

            // Exodus-begin nebula-radar-visualization
            if (!BlipIntersectsView(position, blip.Config, monoViewBounds))
                continue;
            // Exodus-end

            DrawBlipShape(handle, position, box, color, blip.Config, worldRot); // Exodus nebula-radar-visualization
        }

        // Draw hitscan lines from the radar blips system
        var hitscanLines = _blips.GetHitscanLines();
        foreach (var line in hitscanLines)
        {
            var startPosInView = Vector2.Transform(line.Start, worldToView);
            var endPosInView = Vector2.Transform(line.End, worldToView);

            // Only draw lines if at least one endpoint is within view
            if (monoViewBounds.Contains(startPosInView) || monoViewBounds.Contains(endPosInView))
            {
                // Draw the line with the specified thickness and color
                handle.DrawLine(startPosInView, endPosInView, line.Color);

                // For thicker lines, draw multiple lines side by side
                if (line.Thickness > 1.0f)
                {
                    // Calculate perpendicular vector for thickness
                    var dir = (endPosInView - startPosInView).Normalized();
                    var perpendicular = new Vector2(-dir.Y, dir.X) * 0.5f;

                    // Draw additional lines for thickness
                    for (float i = 1; i <= line.Thickness; i += 1.0f)
                    {
                        var offset = perpendicular * i;
                        handle.DrawLine(startPosInView + offset, endPosInView + offset, line.Color);
                        handle.DrawLine(startPosInView - offset, endPosInView - offset, line.Color);
                    }
                }
            }
        }
        #endregion

        //Exodus - ShuttleHooks - Begin
        // Draw lines from grappling gun to target
        DrawGrapLinks(handle, worldToView, monoViewBounds);
        //Exodus - ShuttleHooks - End

        // Exodus-begin territory-marker
        foreach (var blip in rawBlips)
        {
            if (blip.Config.Shape != RadarBlipShape.TerritoryCircle)
                continue;

            var position = Vector2.Transform(_transform.ToMapCoordinates(blip.Position).Position, worldToView);
            DrawTerritoryCircleBlip(handle, position, blip.Config, monoViewBounds);
        }
        // Exodus-end

        DrawSafeZones(handle, worldToView, ourGridId); // Exodus - SafeZone
    }

    protected DetectionLevel GetGridDetected(EntityUid grid)
    {
        if (Detectors != null)
            return _detection.IsGridDetected(grid, Detectors);

        return _consoleEntity == null ? DetectionLevel.Undetected : _detection.IsGridDetected(grid, _consoleEntity.Value);
    }

    // Exodus-begin faction AI radar label
    private string AddFactionAiControlLabel(EntityUid grid, string labelText)
    {
        _factionAiControlQuery.TryGetComponent(grid, out var control);
        return FactionAiControlLabelHelper.AppendToLabel(labelText, control, _prototype);
    }

    // Exodus mass-scanner-perf: span-based multiline sizing avoids Split allocations.
    private Vector2 GetMultilineLabelDimensions(DrawingHandleScreen handle, ReadOnlySpan<char> text, float scale)
    {
        var dimensions = Vector2.Zero;
        var remaining = text;

        while (true)
        {
            var lineEnd = remaining.IndexOf('\n');
            var line = lineEnd >= 0 ? remaining[..lineEnd] : remaining;
            var lineDimensions = handle.GetDimensions(Font, line, scale);
            dimensions.X = MathF.Max(dimensions.X, lineDimensions.X);
            dimensions.Y += lineDimensions.Y;

            if (lineEnd < 0)
                break;

            remaining = remaining[(lineEnd + 1)..];
        }

        return dimensions;
    }

    // Exodus mass-scanner-perf: span-based multiline draw avoids Split allocations.
    private void DrawMultilineLabel(
        DrawingHandleScreen handle,
        Vector2 uiPosition,
        Vector2 labelOffset,
        ReadOnlySpan<char> text,
        float scale,
        Color color)
    {
        var y = labelOffset.Y;
        var remaining = text;

        while (true)
        {
            var lineEnd = remaining.IndexOf('\n');
            var line = lineEnd >= 0 ? remaining[..lineEnd] : remaining;
            handle.DrawString(Font, (uiPosition + new Vector2(labelOffset.X, y)) * UIScale, line, scale, color);
            y += handle.GetDimensions(Font, line, 0.9f).Y;

            if (lineEnd < 0)
                break;

            remaining = remaining[(lineEnd + 1)..];
        }
    }

    // Exodus-end

    // Exodus-begin mass-scanner-perf
    private static bool LabelExtendsBeyondRadar(Vector2 labelPosition, Vector2 labelDimensions, float squaredRadius)
    {
        return labelPosition.LengthSquared() > squaredRadius
            || (labelPosition + new Vector2(labelDimensions.X, 0)).LengthSquared() > squaredRadius
            || (labelPosition + new Vector2(0, labelDimensions.Y)).LengthSquared() > squaredRadius
            || (labelPosition + labelDimensions).LengthSquared() > squaredRadius;
    }

    private bool BlipIntersectsView(Vector2 position, BlipConfig config, Box2 viewBounds)
    {
        var extent = GetBlipScreenExtent(config);
        return extent <= 0f || CircleIntersectsBox(position, extent, viewBounds);
    }

    private float GetBlipScreenExtent(BlipConfig config)
    {
        if (config.Shape == RadarBlipShape.NebulaPolygon && config.Points is { Count: >= 3 })
        {
            var extent = 0f;

            foreach (var point in config.Points)
            {
                var scaled = config.RespectZoom ? point * MinimapScale : point;
                extent = MathF.Max(extent, scaled.Length());
            }

            if (config.InvertFill && config.OuterFillRadius > 0f)
            {
                var outer = config.RespectZoom ? config.OuterFillRadius * MinimapScale : config.OuterFillRadius;
                extent = MathF.Max(extent, outer);
            }

            return extent;
        }

        var bounds = config.Bounds;
        if (config.RespectZoom)
            bounds = new Box2(bounds.BottomLeft * MinimapScale, bounds.TopRight * MinimapScale);

        return bounds.MaxDimension * 0.5f;
    }
    // Exodus-end

    private (Vector2 Top, Vector2 Left, Vector2 Offset) GetSize(Box2Rotated bounds)
    {
        var top = (bounds.TopLeft + bounds.TopRight) * 0.5f;
        var left = (bounds.TopLeft + bounds.BottomLeft) * 0.5f;
        var offset = (bounds.TopRight + bounds.BottomLeft) * 0.5f;

        return (top - offset, left - offset, offset);
    }

    // Exodus nebula-radar-visualization: pass the full config so custom blip shapes can read extra data.
    private void DrawBlipShape(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color, BlipConfig config, Angle worldRotation) // Exodus nebula-radar-visualization
    {
        switch (config.Shape) // Exodus nebula-radar-visualization
        {
            case RadarBlipShape.Circle:
                DrawCircle(handle, position, bounds, color);
                break;
            // Exodus-begin nebula-radar-visualization
            case RadarBlipShape.Ring:
                DrawRing(handle, position, bounds, color);
                break;
            case RadarBlipShape.NebulaPolygon:
                DrawNebulaPolygon(handle, position, config, color, worldRotation);
                break;
            // Exodus-end
            case RadarBlipShape.Square:
                var boxPoints = new Vector2[]
                {
                    position + bounds.TopLeft,
                    position + bounds.TopRight,
                    position + bounds.BottomRight,
                    position + bounds.BottomLeft
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, boxPoints, color);
                break;
            case RadarBlipShape.Triangle:
                var points = new Vector2[]
                {
                    position + bounds.Origin + bounds.Rotation.RotateVec((bounds.TopLeft + bounds.TopRight) * 0.5f - bounds.Origin),
                    position + bounds.BottomLeft,
                    position + bounds.BottomRight
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, points, color);
                break;
            case RadarBlipShape.Star:
                DrawStar(handle, position, bounds, color);
                break;
            case RadarBlipShape.Diamond:
                var size = GetSize(bounds);
                var diamondPoints = new Vector2[]
                {
                    position + size.Offset + size.Top,
                    position + size.Offset + size.Left,
                    position + size.Offset - size.Top,
                    position + size.Offset - size.Left
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, diamondPoints, color);
                break;
            case RadarBlipShape.Hexagon:
                DrawHexagon(handle, position, bounds, color);
                break;
            case RadarBlipShape.Arrow:
                DrawArrow(handle, position, bounds, color);
                break;
        }
    }

    // Exodus mass-scanner-perf: reuse shape buffer instead of allocating per blip draw.
    private void DrawCircle(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int segments = 64;
        var count = segments + 1;
        EnsureShapeDrawBuffer(count);
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i <= segments; i++)
        {
            var angle = i * MathF.Tau / segments;
            var pos = size.Left * MathF.Sin(angle) + size.Top * MathF.Cos(angle);

            _shapeDrawBuffer[i] = offsetPos + pos;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, new Span<Vector2>(_shapeDrawBuffer, 0, count), color);
    }

    // Exodus mass-scanner-perf
    private void EnsureShapeDrawBuffer(int count)
    {
        if (_shapeDrawBuffer.Length < count)
            _shapeDrawBuffer = new Vector2[count];
    }

    // Exodus-begin nebula-radar-visualization
    private void DrawNebulaPolygon(DrawingHandleScreen handle, Vector2 position, BlipConfig config, Color color, Angle worldRotation)
    {
        if (config.Points == null || config.Points.Count < 3)
            return;

        var rotation = (float) -worldRotation.Theta;
        var cos = MathF.Cos(rotation);
        var sin = MathF.Sin(rotation);

        if (config.InvertFill && config.OuterFillRadius > 0f)
        {
            var n = config.Points.Count;
            var ringCount = 2 * (n + 1);
            if (_nebulaFillBuffer.Length < ringCount)
                _nebulaFillBuffer = new Vector2[ringCount];

            for (var i = 0; i <= n; i++)
            {
                var k = i % n;
                var theta = MathF.Tau * k / n;
                // Exodus nebula-radar-visualization: rotate outer ring endpoints into the same frame as the inner contour;
                // otherwise the triangle strip skews and shows diagonal fill stripes when the radar rotates with the shuttle.
                var rawOuter = new Vector2(config.OuterFillRadius * MathF.Cos(theta), config.OuterFillRadius * MathF.Sin(theta)); // Exodus mass-scanner-fix: keep invert-fill outer radius stable in world space.
                var outerPoint = RotateNebulaPoint(rawOuter, cos, sin);
                var innerPoint = RotateNebulaPoint(config.Points[k], cos, sin);

                if (config.RespectZoom)
                {
                    outerPoint *= MinimapScale;
                    innerPoint *= MinimapScale;
                }

                _nebulaFillBuffer[2 * i] = position + (outerPoint with { Y = -outerPoint.Y });
                _nebulaFillBuffer[2 * i + 1] = position + (innerPoint with { Y = -innerPoint.Y });
            }

            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleStrip, new Span<Vector2>(_nebulaFillBuffer, 0, ringCount), color.WithAlpha(NebulaFillAlpha));
        }
        else if (!config.InvertFill)
        {
            var fillCount = config.Points.Count + 2;
            if (_nebulaFillBuffer.Length < fillCount)
                _nebulaFillBuffer = new Vector2[fillCount];

            _nebulaFillBuffer[0] = position;

            for (var i = 0; i < config.Points.Count; i++)
            {
                var point = RotateNebulaPoint(config.Points[i], cos, sin);
                if (config.RespectZoom)
                    point *= MinimapScale;

                _nebulaFillBuffer[i + 1] = position + (point with { Y = -point.Y });
            }

            // TriangleFan does not close the last wedge by itself.
            _nebulaFillBuffer[fillCount - 1] = _nebulaFillBuffer[1];
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, new Span<Vector2>(_nebulaFillBuffer, 0, fillCount), color.WithAlpha(NebulaFillAlpha));
        }

        var lineCount = config.Points.Count + 1;
        if (_nebulaLineBuffer.Length < lineCount)
            _nebulaLineBuffer = new Vector2[lineCount];

        for (var i = 0; i < config.Points.Count; i++)
        {
            var point = RotateNebulaPoint(config.Points[i], cos, sin);
            if (config.RespectZoom)
                point *= MinimapScale;

            _nebulaLineBuffer[i] = position + (point with { Y = -point.Y });
        }

        _nebulaLineBuffer[lineCount - 1] = _nebulaLineBuffer[0];
        handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, new Span<Vector2>(_nebulaLineBuffer, 0, lineCount), color.WithAlpha(0.9f));
    }

    private static Vector2 RotateNebulaPoint(Vector2 point, float cos, float sin)
    {
        return new Vector2(
            point.X * cos - point.Y * sin,
            point.X * sin + point.Y * cos);
    }

    // Exodus mass-scanner-perf: reuse shape buffer instead of allocating per blip draw.
    private void DrawRing(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int segments = 96;
        var count = segments + 1;
        EnsureShapeDrawBuffer(count);
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i <= segments; i++)
        {
            var angle = i * MathF.Tau / segments;
            var pos = size.Left * MathF.Sin(angle) + size.Top * MathF.Cos(angle);

            _shapeDrawBuffer[i] = offsetPos + pos;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, new Span<Vector2>(_shapeDrawBuffer, 0, count), color);
    }
    // Exodus-end

    private void DrawStar(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int points = 5;
        const float innerRatio = 0.4f;
        var vertices = new Vector2[points * 2];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i < points * 2; i++)
        {
            var angle = i * MathF.PI / points;
            var radius = i % 2 == 0 ? 1f : innerRatio;
            vertices[i] = offsetPos + radius * MathF.Sin(angle) * size.Left - radius * MathF.Cos(angle) * size.Top;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawHexagon(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        var vertices = new Vector2[6];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i < 6; i++)
        {
            var angle = i * MathF.PI / 3;
            vertices[i] = offsetPos + MathF.Sin(angle) * size.Top - MathF.Cos(angle) * size.Left;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawArrow(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        var vertices = new Vector2[]
        {
            offsetPos - size.Top,                    // Tip
            offsetPos + size.Left + size.Top * 0.5f, // Left wing
            offsetPos + size.Top,                    // Bottom
            offsetPos - size.Left + size.Top * 0.5f  // Right wing
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawDocks(DrawingHandleScreen handle, EntityUid uid, Matrix3x2 gridToView)
    {
        if (!ShowDocks)
            return;

        const float DockScale = 0.6f;
        var nent = EntManager.GetNetEntity(uid);

        const float sqrt2 = 1.41421356f;
        const float dockRadius = DockScale * sqrt2;
        // Worst-case bounds used to cull a dock:
        Box2 viewBounds = new Box2(-dockRadius, -dockRadius, PixelSize.X + dockRadius, PixelSize.Y + dockRadius); // Frontier: Size<PixelSize
        if (_docks.TryGetValue(nent, out var docks))
        {
            foreach (var state in docks)
            {
                var position = state.Coordinates.Position;

                var positionInView = Vector2.Transform(position, gridToView);
                if (!viewBounds.Contains(positionInView))
                {
                    continue;
                }

                //var color = Color.ToSrgb(Color.Magenta); // Frontier
                var color = Color.ToSrgb(state.HighlightedRadarColor); // Frontier

                var verts = new[]
                {
                    Vector2.Transform(position + new Vector2(-DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(-DockScale, DockScale), gridToView),
                };

                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, color.WithAlpha(0.8f));
                handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
            }

            // Frontier: draw dock labels (done last to appear on top of all docks, still fights with other grids)
            var dockLabelAlpha = GetDockLabelZoomAlpha(); // Exodus - dock-label-fade
            if (dockLabelAlpha <= 0f)
                return;

            var dockLabelColor = _dockLabelColor.WithAlpha(_dockLabelColor.A * dockLabelAlpha); // Exodus - dock-label-fade
            var labeled = new HashSet<string>();
            foreach (var state in docks)
            {
                if (state.LabelName == null || labeled.Contains(state.LabelName))
                    continue;

                var position = state.Coordinates.Position;
                var uiPosition = Vector2.Transform(position, gridToView);

                if (!viewBounds.Contains(uiPosition))
                    continue;

                labeled.Add(state.LabelName);
                var labelDimensions = handle.GetDimensions(Font, state.LabelName, 0.9f);
                handle.DrawString(
                    Font,
                    (uiPosition / UIScale - labelDimensions / 2) * UIScale,
                    state.LabelName,
                    UIScale * 0.9f,
                    dockLabelColor); // Exodus - dock-label-fade
            }
            // End Frontier
        }
    }

    // Exodus-begin dock-label-fade
    private float GetDockLabelZoomAlpha()
    {
        if (WorldRange <= DockLabelFadeOutWorldRange)
            return 1f;

        if (WorldRange >= DockLabelHiddenWorldRange)
            return 0f;

        return 1f - (WorldRange - DockLabelFadeOutWorldRange) / (DockLabelHiddenWorldRange - DockLabelFadeOutWorldRange);
    }
    // Exodus-end

    protected Vector2 InverseScalePosition(Vector2 value)
    {
        var scaledValue = value * UIScale;
        return (scaledValue - MidPointVector) / MinimapScale;
    }

    // Mono
    protected EntityCoordinates GetMouseEntityCoordinates(Vector2 relativePosition)
    {
        if (_coordinates is not { } cord || _rotation is not { } rot)
            return new();

        // multiply by UIScale because UI is Very Intelligent and doesn't scale mouse position for whatever reason
        var screenRelativeWorldPos = InverseMapPosition(relativePosition * UIScale);
        var relativeWorldPos = rot.RotateVec(screenRelativeWorldPos);
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        var coords = cord.Offset((-coordEntRot).RotateVec(relativeWorldPos));
        return coords;
    }

    public class BlipData
    {
        public bool IsOutsideRadarCircle { get; set; }
        public Vector2 UiPosition { get; set; }
        public Vector2 VectorToPosition { get; set; }
        public Color Color { get; set; }
    }

    private const int RadarBlipSize = 15;
    private const int RadarFontSize = 8;

    private void DrawShields(DrawingHandleScreen handle, TransformComponent consoleXform, Matrix3x2 matrix)
    {
        var shields = EntManager.AllEntityQueryEnumerator<ShipShieldVisualsComponent, FixturesComponent, TransformComponent>();
        while (shields.MoveNext(out var uid, out var visuals, out var fixtures, out var xform))
        {
            if (!_xformQuery.TryGetComponent(xform.GridUid, out var parentXform)) // Exodus - SafeZone
                continue;

            if (xform.MapID != consoleXform.MapID)
                continue;

            // Don't draw shields when in FTL
            if (EntManager.HasComponent<FTLComponent>(parentXform.Owner))
                continue;

            var detectionLevel = _consoleEntity == null ? DetectionLevel.Detected : GetGridDetected(parentXform.Owner);
            if (detectionLevel != DetectionLevel.Detected)
                continue;

            var shieldFixture = fixtures.Fixtures.TryGetValue("shield", out var fixture) ? fixture : null;

            if (shieldFixture == null || shieldFixture.Shape is not ChainShape)
                continue;

            ChainShape chain = (ChainShape) shieldFixture.Shape;

            var count = chain.Count;
            var verticies = chain.Vertices;

            var center = _transform.WithEntityId(xform.Coordinates, xform.GridUid.Value).Position;

            for (int i = 1; i < count; i++)
            {
                var v1 = Vector2.Add(center, verticies[i - 1]);
                v1 = Vector2.Transform(v1, parentXform.WorldMatrix); // transform to world matrix
                v1 = Vector2.Transform(v1, matrix); // get back to local matrix for drawing
                v1.Y = -v1.Y;
                v1 = ScalePosition(v1);
                var v2 = Vector2.Add(center, verticies[i]);
                v2 = Vector2.Transform(v2, parentXform.WorldMatrix);
                v2 = Vector2.Transform(v2, matrix);
                v2.Y = -v2.Y;
                v2 = ScalePosition(v2);
                handle.DrawLine(v1, v2, visuals.ShieldColor);
            }
        }
    }

    // Exodus - ShuttleHooks - Start
    private void DrawGrapLinks(DrawingHandleScreen handle, Matrix3x2 worldToView, Box2 monoViewBounds)
    {
        foreach ( var link in _grapLinks)
        {
            if (!_xformQuery.TryGetComponent(EntManager.GetEntity(link.Gun), out var gunXform)
                || !_xformQuery.TryGetComponent(EntManager.GetEntity(link.Target), out var targetXform))
                continue;

            var gunPosInView = Vector2.Transform(_transform.GetWorldPosition(EntManager.GetEntity(link.Gun)), worldToView);
            var targetPosInView = Vector2.Transform(_transform.GetWorldPosition(EntManager.GetEntity(link.Target)), worldToView);

            if (monoViewBounds.Contains(gunPosInView) || monoViewBounds.Contains(targetPosInView))
            {
                handle.DrawLine(gunPosInView, targetPosInView, Color.Magenta);
            }
        }
    }
    // Exodus - ShuttleHooks - End

    // Exodus-begin territory-marker
    private void DrawTerritoryCircleBlip(DrawingHandleScreen handle, Vector2 position, BlipConfig config, Box2 viewBounds)
    {
        var screenRadius = GetTerritoryScreenRadius(config);
        if (screenRadius <= 0f)
            return;

        if (!CircleIntersectsBox(position, screenRadius, viewBounds))
            return;

        handle.DrawCircle(position, screenRadius, config.Color);
        handle.DrawCircle(position, screenRadius, config.BorderColor, filled: false);

        DrawTerritoryText(handle, position, screenRadius, config, viewBounds);
    }

    private float GetTerritoryScreenRadius(BlipConfig config)
    {
        var radius = config.Bounds.MaxDimension * 0.5f;
        if (radius < 1f)
            return 0f;

        return config.RespectZoom
            ? radius * MinimapScale
            : radius;
    }

    private void DrawTerritoryText(DrawingHandleScreen handle, Vector2 territoryCenter, float screenRadius, BlipConfig config, Box2 viewBounds)
    {
        if (config.Label == null)
            return;

        // Exodus mass-scanner-perf: cache localized territory labels across frames.
        if (!_territoryLabelCache.TryGetValue(config.Label, out var text))
        {
            text = Loc.GetString(config.Label);
            _territoryLabelCache[config.Label] = text;
        }

        if (string.IsNullOrEmpty(text))
            return;

        var worldRadius = config.Bounds.MaxDimension * 0.5f;
        if (worldRadius < 1f)
            return;

        // Fixed 45 degrees in screen space; stays still when ship rotates.
        // Text positions are generated with screen spacing that scales with MinimapScale
        // (screenStepLen = TerritoryTextWorldRepeat * MinimapScale) and always centered on the ring.
        // This makes the pattern fully static relative to the ring: same relative positions and density
        // no matter how you pan or zoom the mass scanner.
        const float angle45 = MathF.PI * 0.25f;
        var textAngle = new Angle(angle45);
        var screenDir = new Vector2(MathF.Cos(angle45), MathF.Sin(angle45));
        var perpDir = new Vector2(-screenDir.Y, screenDir.X);

        var textScale = UIScale * 1.2f;
        var baseAlpha = 0.35f;
        var textColor = new Color(0.65f, 0.65f, 0.65f);
        var textDims = handle.GetDimensions(Font, text, textScale);
        var textDrawOffset = new Vector2(
            -textDims.X * 0.5f,
            -textDims.Y * 0.5f);
        var halfDiag = MathF.Sqrt(textDims.X * textDims.X + textDims.Y * textDims.Y) * 0.5f;
        var zoomAlpha = GetTerritoryTextZoomAlpha(screenRadius, halfDiag, viewBounds);
        if (zoomAlpha <= 0f)
            return;

        // Fade text near the circle edge (in screen pixels).
        var fadeEnd = screenRadius - halfDiag;
        if (fadeEnd <= 0f)
            return;

        var fadeStart = MathF.Max(0f, fadeEnd - halfDiag * 6f);
        var edgeFadeRange = fadeEnd - fadeStart;

        // SetTransform uses screen coordinates, not control-local coordinates.
        var screenOffset = (Vector2) GlobalPixelPosition;
        var prevTransform = handle.GetTransform();

        // Fixed world-space repeat for the diagonal pattern.
        // See TerritoryTextWorldRepeat (top of territory section) for tuning.
        var screenStepLen = TerritoryTextWorldRepeat * MinimapScale;
        if (screenStepLen <= 0f)
            return;

        var stepDir = screenDir * screenStepLen;
        var stepPerp = perpDir * screenStepLen;

        // How many steps we need to search in index space to cover the territory.
        var maxIndex = (int)((worldRadius / TerritoryTextWorldRepeat) * 1.8f) + 4;
        var textCullBounds = viewBounds.Enlarged(halfDiag);

        GetTerritoryTextIndexRange(textCullBounds, territoryCenter, screenDir, screenStepLen, out var minRow, out var maxRow);
        GetTerritoryTextIndexRange(textCullBounds, territoryCenter, perpDir, screenStepLen, out var minCol, out var maxCol);

        minRow = Math.Max(minRow, -maxIndex);
        maxRow = Math.Min(maxRow, maxIndex);
        minCol = Math.Max(minCol, -maxIndex);
        maxCol = Math.Min(maxCol, maxIndex);

        if (minRow > maxRow || minCol > maxCol)
            return;

        // Use one index as "row" for the stagger (to keep the old nice diagonal offset look).
        for (var row = minRow; row <= maxRow; row++)
        {
            var stagger = (row % 2 == 0) ? 0f : (screenStepLen * 0.5f);
            for (var col = minCol; col <= maxCol; col++)
            {
                var pos = territoryCenter + (row * stepDir) + (col * stepPerp) + (stagger * perpDir);  // stagger along the perp for visual

                if (!textCullBounds.Contains(pos))
                    continue;

                var distSquared = (pos - territoryCenter).LengthSquared();
                if (distSquared >= fadeEnd * fadeEnd)
                    continue;

                var dist = MathF.Sqrt(distSquared);
                var edgeAlpha = dist <= fadeStart || edgeFadeRange <= 0f
                    ? 1f
                    : 1f - (dist - fadeStart) / edgeFadeRange;
                var alpha = baseAlpha * zoomAlpha * edgeAlpha;

                if (alpha <= 0f)
                    continue;

                handle.SetTransform(screenOffset + pos, textAngle);
                handle.DrawString(Font, textDrawOffset, text, textScale, textColor.WithAlpha(alpha));
            }
        }

        handle.SetTransform(prevTransform);
    }

    private static bool CircleIntersectsBox(Vector2 center, float radius, Box2 box)
    {
        var closest = new Vector2(
            Math.Clamp(center.X, box.Left, box.Right),
            Math.Clamp(center.Y, box.Bottom, box.Top));

        return (closest - center).LengthSquared() <= radius * radius;
    }

    private static float GetTerritoryTextZoomAlpha(float screenRadius, float halfDiag, Box2 viewBounds)
    {
        var fadeInStart = halfDiag * TerritoryTextFadeInDiagMultiplier;
        var fadeInEnd = halfDiag * TerritoryTextFullDiagMultiplier;

        if (screenRadius <= fadeInStart)
            return 0f;

        var fadeInAlpha = screenRadius >= fadeInEnd
            ? 1f
            : (screenRadius - fadeInStart) / (fadeInEnd - fadeInStart);

        var viewWidth = MathF.Abs(viewBounds.Right - viewBounds.Left);
        var viewHeight = MathF.Abs(viewBounds.Top - viewBounds.Bottom);
        var viewDiag = MathF.Sqrt(viewWidth * viewWidth + viewHeight * viewHeight);
        if (viewDiag <= 0f)
            return fadeInAlpha;

        var fadeOutStart = viewDiag * TerritoryTextFadeOutViewDiagMultiplier;
        var fadeOutEnd = viewDiag * TerritoryTextHiddenViewDiagMultiplier;

        if (screenRadius >= fadeOutEnd)
            return 0f;

        var fadeOutAlpha = screenRadius <= fadeOutStart
            ? 1f
            : 1f - (screenRadius - fadeOutStart) / (fadeOutEnd - fadeOutStart);

        return fadeInAlpha * fadeOutAlpha;
    }

    private static void GetTerritoryTextIndexRange(Box2 bounds, Vector2 center, Vector2 axis, float step, out int min, out int max)
    {
        var topLeft = Vector2.Dot(bounds.TopLeft - center, axis);
        var topRight = Vector2.Dot(bounds.TopRight - center, axis);
        var bottomLeft = Vector2.Dot(bounds.BottomLeft - center, axis);
        var bottomRight = Vector2.Dot(bounds.BottomRight - center, axis);

        var minProjection = MathF.Min(MathF.Min(topLeft, topRight), MathF.Min(bottomLeft, bottomRight));
        var maxProjection = MathF.Max(MathF.Max(topLeft, topRight), MathF.Max(bottomLeft, bottomRight));

        min = (int)MathF.Floor(minProjection / step) - 2;
        max = (int)MathF.Ceiling(maxProjection / step) + 2;
    }
    // Exodus-end

    // Exodus - SafeZone - Start
    private void DrawSafeZones(DrawingHandleScreen handle, Matrix3x2 worldToView, EntityUid? ourGridUid)
    {
        if (ourGridUid is not { } ourGrid)
            return;

        var ourGridPos = _transform.GetMapCoordinates(ourGrid);

        foreach (var grid in _grids)
        {
            if (!_zoneQuery.TryGetComponent(grid.Owner, out var zoneComp))
                continue;

            var gridPos = _transform.GetMapCoordinates(grid.Owner);

            if (gridPos.MapId != ourGridPos.MapId)
                continue;

            var gridPosInView = Vector2.Transform(gridPos.Position, worldToView);

            handle.DrawCircle(gridPosInView, zoneComp.Radius * MinimapScale, zoneComp.Color, filled: false);

            if (ourGridPos.InRange(gridPos, zoneComp.Radius) && zoneComp.ShouldShowText)
            {
                var textMargin = 6f;
                var pos = new Vector2(textMargin, textMargin);

                handle.DrawString(Font, pos * UIScale, Loc.GetString(zoneComp.Text), UIScale * 2f, zoneComp.TextColor);
            }
        }
    }
    // Exodus - SafeZone - End
}
