using System.Buffers;
using System.Numerics;
using Content.Client._Exodus.Nebula; // Exodus nebula-ftl-map
using Content.Shared._Exodus.NPC.Components; // Exodus faction AI FTL map label
using Content.Client._Mono.Radar; // Exodus nebula-ftl-map
using Content.Client._Exodus.Territory; // Exodus territory POI colors
using Content.Client.Shuttles.Systems;
using Content.Shared._Mono.Company;
using Content.Shared._Mono.Detection;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.UI.MapObjects;
using Content.Shared._Exodus.Territory; // Exodus territory visuals on BSS jump map
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleMapControl : BaseShuttleControl
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IInputManager _inputs = default!;
    [Dependency] private IMapManager _mapManager = default!;
    [Dependency] private IEntityManager _entManager = default!; // Frontier
    private readonly DetectionSystem _detection; // Mono
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;
    private readonly TerritoryPoiColorSystem _territoryPoiColors; // Exodus territory POI colors
    // Exodus-begin BSS map hot-path component queries
    private readonly EntityQuery<CompanyComponent> _companyQuery;
    private readonly EntityQuery<FactionAiControlledGridComponent> _factionAiControlQuery;
    private readonly EntityQuery<GridTerritoryComponent> _gridTerritoryQuery;
    private readonly EntityQuery<IFFComponent> _iffQuery;
    private readonly EntityQuery<MapGridComponent> _mapGridQuery;
    private readonly EntityQuery<TransformComponent> _transformQuery;
    // Exodus-end

    protected override bool Draggable => true;

    protected override float ScrollSensitivity => 4f;

    public bool ShowBeacons = true;
    public MapId ViewingMap = MapId.Nullspace;

    private EntityUid? _console; // Mono
    private EntityUid? _shuttleEntity;

    private readonly Font _font;

    private readonly EntityQuery<PhysicsComponent> _physicsQuery;

    /// <summary>
    /// Toggles FTL mode on. This shows a pre-vis for FTLing a grid.
    /// </summary>
    public bool FtlMode;

    /// <summary>
    /// Shows only the FTL range circle without cursor targeting elements.
    /// </summary>
    public bool ShowFTLRangeOnly;

    /// <summary>
    /// Mono - Whether to show FTL range at all.
    /// </summary>
    public bool ShowFTLRange = true;

    /// <summary>
    /// Mono - Whether to ignore FTL obstructions and range for preview display.
    /// </summary>
    public bool NoFTLRange = false;

    private Angle _ftlAngle;

    /// <summary>
    /// Are we currently in FTL.
    /// </summary>
    public bool InFtl;

    /// <summary>
    /// Raised when a request to FTL to a particular spot is raised.
    /// </summary>
    public event Action<MapCoordinates, Angle>? RequestFTL;

    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    /// <summary>
    /// Set every draw to determine the beacons that are clickable for mouse events
    /// </summary>
    private List<IMapObject> _beacons = new();

    // Per frame data to avoid re-allocating
    private readonly List<IMapObject> _mapObjects = new();
    private readonly Dictionary<Color, List<Vector2>> _verts = new();
    private readonly Dictionary<Color, List<Vector2>> _edges = new();
    private readonly Dictionary<Color, List<(Vector2 Position, string Text, bool HasLabel, EntityUid? GridUid)>> _strings = new(); // Exodus territory POI colors
    private readonly List<ShuttleExclusionObject> _viewportExclusions = new();
    private const float BssMapBackgroundTileScale = 30f; // Exodus reduce BSS map background tile churn when zoomed out

    public ShuttleMapControl() : base(256f, 28000f, 512f) // Exodus nebula-ftl-map
    {
        RobustXamlLoader.Load(this);
        _detection = EntManager.System<DetectionSystem>(); // Mono
        _blips = EntManager.System<RadarBlipsSystem>(); // Exodus nebula-ftl-map
        _nebula = EntManager.System<NebulaSystem>(); // Exodus nebula-ftl-map
        _shuttles = EntManager.System<ShuttleSystem>();
        _xformSystem = EntManager.System<SharedTransformSystem>();
        _territoryPoiColors = EntManager.System<TerritoryPoiColorSystem>(); // Exodus territory POI colors
        var cache = IoCManager.Resolve<IResourceCache>();

        _physicsQuery = EntManager.GetEntityQuery<PhysicsComponent>();
        // Exodus-begin BSS map hot-path component queries
        _companyQuery = EntManager.GetEntityQuery<CompanyComponent>();
        _factionAiControlQuery = EntManager.GetEntityQuery<FactionAiControlledGridComponent>();
        _gridTerritoryQuery = EntManager.GetEntityQuery<GridTerritoryComponent>();
        _iffQuery = EntManager.GetEntityQuery<IFFComponent>();
        _mapGridQuery = EntManager.GetEntityQuery<MapGridComponent>();
        _transformQuery = EntManager.GetEntityQuery<TransformComponent>();
        // Exodus-end

        _font = new VectorFont(cache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSans-Regular.ttf"), 10);
    }

    public void SetMap(MapId mapId, Vector2 offset, bool recentering = false)
    {
        ViewingMap = mapId;
        TargetOffset = offset;
        Recentering = recentering;
    }

    // Mono
    public void SetConsole(EntityUid? console)
    {
        _console = console;
    }

    public void SetShuttle(EntityUid? entity)
    {
        _shuttleEntity = entity;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (FtlMode && ViewingMap != MapId.Nullspace)
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                var mapUid = _mapManager.GetMapEntityId(ViewingMap);

                var beaconsOnly = EntManager.TryGetComponent(mapUid, out FTLDestinationComponent? destComp) &&
                                  destComp.BeaconsOnly;

                var mapTransform = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);

                if (beaconsOnly && TryGetBeacon(_beacons, mapTransform, args.RelativePixelPosition, PixelRect, out var foundBeacon, out _))
                {
                    RequestBeaconFTL?.Invoke(foundBeacon.Entity, _ftlAngle);
                }
                else
                {
                    // We'll send the "adjusted" position and server will adjust it back when relevant.
                    var mapCoords = new MapCoordinates(InverseMapPosition(args.RelativePixelPosition), ViewingMap);

                    RequestFTL?.Invoke(mapCoords, _ftlAngle);
                }
            }
        }

        base.KeyBindUp(args);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        // Scroll handles FTL rotation if you're in FTL mode.
        if (FtlMode)
        {
            _ftlAngle -= Angle.FromDegrees(15f) * args.Delta.Y; // Mono Edit: Subtract instead of add to preserve clockwise rotation when scrolling up. (positive angles are actually counter-clockwise)
            _ftlAngle = _ftlAngle.Reduced();
            return;
        }

        base.MouseWheel(args);
    }

    private void DrawParallax(DrawingHandleScreen handle)
    {
        if (_shuttleEntity is not { } shuttle ||
            !_transformQuery.TryGetComponent(shuttle, out var shuttleXform) ||
            shuttleXform.MapUid == null)
        {
            return;
        }

        // TODO: Figure out how the fuck to make this common between the 3 slightly different parallax methods and move to parallaxsystem.
        // Draw background texture
        var tex = _shuttles.GetTexture(shuttleXform.MapUid.Value);

        // Size of the texture in world units.
        var size = tex.Size * MinimapScale * BssMapBackgroundTileScale; // Exodus reduce BSS map background tile churn when zoomed out
        if (size.X <= 0f || size.Y <= 0f)
            return;

        var position = ScalePosition(new Vector2(-Offset.X, Offset.Y));
        var slowness = 1f;

        // The "home" position is the effective origin of this layer.
        // Parallax shifting is relative to the home, and shifts away from the home and towards the Eye centre.
        // The effects of this are such that a slowness of 1 anchors the layer to the centre of the screen, while a slowness of 0 anchors the layer to the world.
        // (For values 0.0 to 1.0 this is in effect a lerp, but it's deliberately unclamped.)
        // The ParallaxAnchor adapts the parallax for station positioning and possibly map-specific tweaks.
        var home = Vector2.Zero;
        var scrolled = Vector2.Zero;

        // Origin - start with the parallax shift itself.
        var originBL = (position - home) * slowness + scrolled;

        // Place at the home.
        originBL += home;

        // Centre the image.
        originBL -= size / 2;

        // Remove offset so we can floor.
        var botLeft = new Vector2(0f, 0f);
        var topRight = botLeft + PixelSize;

        var flooredBL = botLeft - originBL;

        // Floor to background size.
        flooredBL = (flooredBL / size).Floored() * size;

        // Re-offset.
        flooredBL += originBL;

        for (var x = flooredBL.X; x < topRight.X; x += size.X)
        {
            for (var y = flooredBL.Y; y < topRight.Y; y += size.Y)
            {
                handle.DrawTextureRect(tex, new UIBox2(x, y, x + size.X, y + size.Y));
            }
        }
    }

    /// <summary>
    /// Gets the map objects that intersect the viewport.
    /// </summary>
    /// <param name="mapObjects"></param>
    /// <returns></returns>
    private List<IMapObject> GetViewportMapObjects(Matrix3x2 matty, List<IMapObject> mapObjects)
    {
        var results = new List<IMapObject>();
        var enlargement = new Vector2i((int) (16 * UIScale), (int) (16 * UIScale));
        var viewBox = new UIBox2i(Vector2i.Zero - enlargement, PixelSize + enlargement);

        foreach (var mapObj in mapObjects)
        {
            // If it's a grid-map skip it.
            if (mapObj is GridMapObject gridObj && (EntManager.HasComponent<MapComponent>(gridObj.Entity) || !_entManager.EntityExists(gridObj.Entity))) // Frontier: add EntityExists
                continue;

            var mapCoords = _shuttles.GetMapCoordinates(mapObj);

            var relativePos = Vector2.Transform(mapCoords.Position, matty);
            relativePos = relativePos with { Y = -relativePos.Y };
            var uiPosition = ScalePosition(relativePos);

            if (!viewBox.Contains(uiPosition.Floored()))
                continue;

            results.Add(mapObj);
        }

        return results;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (ViewingMap == MapId.Nullspace)
            return;

        var mapObjects = _mapObjects;
        DrawRecenter();

        if (InFtl || mapObjects.Count == 0)
        {
            DrawBacking(handle);
            DrawNoSignal(handle);
            return;
        }

        DrawParallax(handle);

        var viewedMapUid = _mapManager.GetMapEntityId(ViewingMap);
        var matty = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);
        var realTime = _timing.RealTime;
        var viewBox = new Box2(Offset - WorldRangeVector, Offset + WorldRangeVector);
        var viewportObjects = GetViewportMapObjects(matty, mapObjects);
        _viewportExclusions.Clear();
        var controlViewBounds = GetControlViewBounds(); // Exodus territory rings need viewport culling before grid batching

        DrawNebulaBlips(handle, matty); // Exodus nebula-ftl-map

        // Draw our FTL range + no FTL zones
        // Do it up here because we want this layered below most things.
        if ((FtlMode || ShowFTLRangeOnly) && ShowFTLRange) // Mono
        {
            if (_shuttleEntity is { } shuttle &&
                _transformQuery.TryGetComponent(shuttle, out var shuttleXform))
            {
                var gridUid = shuttle;
                var gridPhysics = _physicsQuery.GetComponent(gridUid);
                var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                gridPos = Maps.GetGridPosition((gridUid, gridPhysics), gridPos, gridRot);

                var gridRelativePos = Vector2.Transform(gridPos, matty);
                gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                var gridUiPos = ScalePosition(gridRelativePos);

                var range = _shuttles.GetFTLRange(gridUid);
                range *= MinimapScale;
                handle.DrawCircle(gridUiPos, range, Color.Gold, filled: false);
            }
        }

        var exclusionColor = Color.Red;

        // Exclusions need a bumped range so we check all the ones on the map.
        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleExclusionObject exclusion)
                continue;

            // Check if it even intersects the viewport.
            var coords = EntManager.GetCoordinates(exclusion.Coordinates);
            var mapCoords = _xformSystem.ToMapCoordinates(coords);
            var enlargedBounds = viewBox.Enlarged(exclusion.Range);

            if (mapCoords.MapId != ViewingMap ||
                !enlargedBounds.Contains(mapCoords.Position))
            {
                continue;
            }

            var adjustedPos = Vector2.Transform(mapCoords.Position, matty);
            var localPos = ScalePosition(adjustedPos with { Y = -adjustedPos.Y });
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor.WithAlpha(0.05f));
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor, filled: false);

            _viewportExclusions.Add(exclusion);
        }

        _verts.Clear();
        _edges.Clear();
        _strings.Clear();

        DrawTerritoryRings(handle, mapObjects, matty, controlViewBounds); // Exodus territory influence rings

        // Add beacons if relevant.
        var beaconsOnly = _shuttles.IsBeaconMap(viewedMapUid);
        var controlLocalBounds = PixelRect;
        _beacons.Clear();

        if (ShowBeacons)
        {
            var beaconColor = Color.AliceBlue;

            foreach (var (beaconName, coords, mapO) in GetBeacons(viewportObjects, matty, controlLocalBounds))
            {
                var localPos = Vector2.Transform(coords.Position, matty);
                localPos = localPos with { Y = -localPos.Y };
                var beaconUiPos = ScalePosition(localPos);
                var mapObject = GetMapObject(localPos, Angle.Zero, scale: 0.75f, scalePosition: true);

                // Get company color if the beacon has it
                var displayColor = beaconColor;
                if (mapO is GridMapObject gridObj &&
                    _companyQuery.TryGetComponent(gridObj.Entity, out var companyComp) &&
                    !string.IsNullOrEmpty(companyComp.CompanyName) &&
                    PrototypeManager.TryIndex<CompanyPrototype>(companyComp.CompanyName, out var beaconCompanyProto))
                {
                    displayColor = Color.FromSrgb(beaconCompanyProto.Color);
                }

                var existingVerts = _verts.GetOrNew(displayColor);
                var existingEdges = _edges.GetOrNew(displayColor);

                AddMapObject(existingEdges, existingVerts, mapObject);
                _beacons.Add(mapO);

                var existingStrings = _strings.GetOrNew(displayColor);
                existingStrings.Add((beaconUiPos, beaconName, true, null)); // Exodus territory POI colors
            }
        }

        foreach (var mapObj in viewportObjects)
        {
            if (mapObj is not GridMapObject gridObj || !_mapGridQuery.TryGetComponent(gridObj.Entity, out var mapGrid))
                continue;

            Entity<MapGridComponent> grid = (gridObj.Entity, mapGrid);
            IFFComponent? iffComp = null;

            // Rudimentary IFF for now, if IFF hiding on then we don't show on the map at all
            if (grid.Owner != _shuttleEntity &&
                _iffQuery.TryGetComponent(grid.Owner, out iffComp) &&
                (iffComp.Flags & IFFFlags.Hide) != 0x0)
            {
                continue;
            }

            // Mono
            var hideLabel = iffComp != null && (iffComp.Flags & IFFFlags.HideLabel) != 0x0;
            var detectionLevel = _console == null ? DetectionLevel.Detected : _detection.IsGridDetected(grid.Owner, _console.Value);
            var detected = detectionLevel != DetectionLevel.Undetected || !hideLabel;
            var blipOnly = detectionLevel != DetectionLevel.Detected;
            if (!detected)
                continue;

            var hideColor = hideLabel && iffComp != null && (iffComp.Flags & IFFFlags.AlwaysShowColor) == 0x0;
            var gridColor = hideColor ? blipOnly ? Color.Orange : Color.White : _shuttles.GetIFFColor(grid, self: _shuttleEntity == grid.Owner, component: iffComp);
            if (!hideColor && _territoryPoiColors.TryGetColor(grid.Owner, out var territoryPoiColor))
                gridColor = territoryPoiColor; // Exodus territory POI colors

            var existingVerts = _verts.GetOrNew(gridColor);
            var existingEdges = _edges.GetOrNew(gridColor);

            var gridPhysics = _physicsQuery.GetComponent(grid.Owner);
            var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(grid.Owner);
            gridPos = Maps.GetGridPosition((grid, gridPhysics), gridPos, gridRot);

            var gridRelativePos = Vector2.Transform(gridPos, matty);
            gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
            var gridUiPos = ScalePosition(gridRelativePos);

            // Exodus-begin territory icons on the BSS map:
            // normal grids keep the default diamond, territory grids use radius-based polygons.
            ValueList<Vector2> mapObject;
            if (_gridTerritoryQuery.TryGetComponent(grid.Owner, out var terr) && terr.Radius > 0)
            {
                mapObject = GetTerritoryMapObject(gridRelativePos, Angle.Zero, terr.Radius, scalePosition: true);
                AddMapPolygon(existingEdges, existingVerts, mapObject);
            }
            else
            {
                mapObject = GetMapObject(gridRelativePos, Angle.Zero, scalePosition: true);
                AddMapObject(existingEdges, existingVerts, mapObject);
            }
            // Exodus-end

            // Mono - now always has label
            // Text
            // if (iffComp != null && (iffComp.Flags & IFFFlags.HideLabel) != 0x0)
            //    continue;

            // Force drawing it at this point.
            // Mono
            var iffText = hideLabel ?
                detectionLevel == DetectionLevel.PartialDetected ?
                    Loc.GetString($"shuttle-console-signature-infrared")
                    : _detection.HandleUnknownMassLabel(grid.Owner)
                : _shuttles.GetIFFLabel(grid, self: true, component: iffComp);

            if (string.IsNullOrEmpty(iffText))
                continue;

            if (!hideLabel)
                iffText = AddFactionAiControlLabel(grid.Owner, iffText); // Exodus faction AI FTL map label

            var existingStrings = _strings.GetOrNew(gridColor);
            existingStrings.Add((gridUiPos, iffText, !hideLabel, grid.Owner)); // Exodus territory POI colors
        }

        // Batch the colors whoopie
        // really only affects forks with lots of grids.
        foreach (var (color, sendVerts) in _verts)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, sendVerts, color.WithAlpha(0.05f));
        }

        foreach (var (color, sendEdges) in _edges)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.LineList, sendEdges, color);
        }

        // Exodus-begin faction/company label colors:
        // labels are batched with the grid uid so draw-time color overrides can match the final label visibility.
        foreach (var (color, sendStrings) in _strings)
        {
            var adjustedColor = Color.FromSrgb(color);

            foreach (var (gridUiPos, iffText, hasLabel, gridUid) in sendStrings)
            {
                // Get company color if entity has CompanyComponent
                var displayColor = adjustedColor;
                if (hasLabel &&
                    gridUid is { } labelGrid &&
                    _companyQuery.TryGetComponent(labelGrid, out var companyComp) &&
                    !string.IsNullOrEmpty(companyComp.CompanyName) &&
                    PrototypeManager.TryIndex<CompanyPrototype>(companyComp.CompanyName, out var gridCompanyProto))
                {
                    displayColor = Color.FromSrgb(gridCompanyProto.Color);
                }

                DrawMapObjectLabel(handle, gridUiPos, iffText, displayColor); // Exodus faction AI FTL map label
            }
        }
        // Exodus-end

        var mousePos = _inputs.MouseScreenPosition;
        var mouseLocalPos = GetLocalPosition(mousePos);

        // Draw dotted line from our own shuttle entity to mouse.
        if (FtlMode && !ShowFTLRangeOnly)
        {
            if (mousePos.Window != WindowId.Invalid)
            {
                // If mouse inbounds then draw it.
                if (_shuttleEntity is { } shuttle &&
                    controlLocalBounds.Contains(mouseLocalPos.Floored()) &&
                    _transformQuery.TryGetComponent(shuttle, out var shuttleXform) &&
                    shuttleXform.MapID != MapId.Nullspace)
                {
                    // If it's a beacon only map then snap the mouse to a nearby spot.
                    ShuttleBeaconObject foundBeacon = default;

                    // Check for beacons around mouse and snap to that.
                    if (beaconsOnly && TryGetBeacon(viewportObjects, matty, mouseLocalPos, controlLocalBounds, out foundBeacon, out var foundLocalPos))
                    {
                        mouseLocalPos = foundLocalPos;
                    }

                    var grid = _mapGridQuery.GetComponent(shuttle);

                    var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                    gridPos = Maps.GetGridPosition(shuttle, gridPos, gridRot);

                    // do NOT apply LocalCenter operation here because it will be adjusted in FTLFree.
                    var mouseMapPos = InverseMapPosition(mouseLocalPos);

                    // Exodus-begin nebula-ftl-map
                    var targetCoordinates = new EntityCoordinates(viewedMapUid, mouseMapPos);
                    var ftlFree = (!beaconsOnly || foundBeacon != default) &&
                                  _shuttles.FTLFree(shuttle, targetCoordinates, _ftlAngle, _viewportExclusions) &&
                                  CanFTLToNebulaPreview(shuttle, targetCoordinates, _ftlAngle)
                                  || NoFTLRange;
                    // Exodus-end

                    var color = ftlFree ? Color.LimeGreen : Color.Magenta;

                    var gridRelativePos = Vector2.Transform(gridPos, matty);
                    gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                    var gridUiPos = ScalePosition(gridRelativePos);

                    // Draw FTL buffer around the mouse.
                    var ourFTLBuffer = _shuttles.GetFTLBufferRange(shuttle, grid);
                    ourFTLBuffer *= MinimapScale;
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, Color.Magenta.WithAlpha(0.01f));
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, Color.Magenta, filled: false);

                    // Draw line from our shuttle to target
                    // Might need to clip the line if it's too far? But my brain wasn't working so F.
                    handle.DrawDottedLine(gridUiPos, mouseLocalPos, color, (float)realTime.TotalSeconds * 30f);

                    // Draw shuttle pre-vis
                    var mouseVerts = GetMapObject(mouseLocalPos, -_ftlAngle, scale: MinimapScale); // Mono Edit: UI controls and the map are in different coordinate orientations, so the angle has to be negated. (shuttle Y is UI control -Y)

                    handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, mouseVerts.Span, color.WithAlpha(0.05f));
                    handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, mouseVerts.Span, color);

                    // Draw a notch indicating direction.
                    var ftlLength = GetMapObjectRadius() + 16f;
                    var ftlEnd = mouseLocalPos + (-_ftlAngle).RotateVec(new Vector2(0f, -ftlLength)); // Mono Edit: UI controls and the map are in different coordinate orientations, so the angle has to be negated. (shuttle Y is UI control -Y)

                    handle.DrawLine(mouseLocalPos, ftlEnd, color);
                }
            }
        }

        // Draw the coordinates
        var mapOffset = MidPointVector;

        if (mousePos.Window != WindowId.Invalid &&
            controlLocalBounds.Contains(mouseLocalPos.Floored()))
        {
            mapOffset = mouseLocalPos;
        }

        mapOffset = InverseMapPosition(mapOffset);
        var coordsText = $"{mapOffset.X:0.0}, {mapOffset.Y:0.0}";

        // Get company color if available
        var coordColor = Color.White;
        if (_shuttleEntity != null &&
            _companyQuery.TryGetComponent(_shuttleEntity.Value, out var shipCompanyComp) &&
            !string.IsNullOrEmpty(shipCompanyComp.CompanyName) &&
            PrototypeManager.TryIndex<CompanyPrototype>(shipCompanyComp.CompanyName, out var shipCompanyProto))
        {
            coordColor = shipCompanyProto.Color;
        }

        DrawData(handle, coordsText, coordColor);
    }

    private void AddMapObject(List<Vector2> edges, List<Vector2> verts, ValueList<Vector2> mapObject)
    {
        var bottom = mapObject[0];
        var right = mapObject[1];
        var top = mapObject[2];
        var left = mapObject[3];

        // Diamond interior
        verts.Add(bottom);
        verts.Add(right);
        verts.Add(top);

        verts.Add(bottom);
        verts.Add(top);
        verts.Add(left);

        // Diamond edges
        edges.Add(bottom);
        edges.Add(right);
        edges.Add(right);
        edges.Add(top);
        edges.Add(top);
        edges.Add(left);
        edges.Add(left);
        edges.Add(bottom);
    }

    /// <summary>
    /// Returns the beacons that intersect the viewport.
    /// </summary>
    private IEnumerable<(string Beacon, MapCoordinates Coordinates, IMapObject MapObject)> GetBeacons(List<IMapObject> mapObjs, Matrix3x2 mapTransform, UIBox2i area)
    {
        foreach (var mapO in mapObjs)
        {
            if (mapO is not ShuttleBeaconObject beacon)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beacon.Coordinates));
            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with {Y = -position.Y});

            // If beacon not on screen then ignore it.
            if (!area.Contains(localPos.Floored()))
                continue;

            yield return (beacon.Name, beaconCoords, mapO);
        }
    }

    private float GetMapObjectRadius(float scale = 1f) => WorldRange / 40f * scale;

    private ValueList<Vector2> GetMapObject(Vector2 localPos, Angle angle, float scale = 1f, bool scalePosition = false)
    {
        // Constant size diamonds
        var diamondRadius = GetMapObjectRadius();

        var mapObj = new ValueList<Vector2>(4)
        {
            localPos + angle.RotateVec(new Vector2(0f, -2f * diamondRadius)) * scale,
            localPos + angle.RotateVec(new Vector2(diamondRadius, 0f)) * scale,
            localPos + angle.RotateVec(new Vector2(0f, 2f * diamondRadius)) * scale,
            localPos + angle.RotateVec(new Vector2(-diamondRadius, 0f)) * scale,
        };

        if (scalePosition)
        {
            for (var i = 0; i < mapObj.Count; i++)
            {
                mapObj[i] = ScalePosition(mapObj[i]);
            }
        }

        return mapObj;
    }

    private bool TryGetBeacon(IEnumerable<IMapObject> mapObjects, Matrix3x2 mapTransform, Vector2 mousePos, UIBox2i area, out ShuttleBeaconObject foundBeacon, out Vector2 foundLocalPos)
    {
        // In pixels
        const float BeaconSnapRange = 32f;
        float nearestValue = float.MaxValue;
        foundLocalPos = Vector2.Zero;
        foundBeacon = default;

        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleBeaconObject beaconObj)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beaconObj.Coordinates));

            if (beaconCoords.MapId != ViewingMap)
                continue;

            // Invalid beacon?
            if (!_shuttles.CanFTLBeacon(beaconObj.Coordinates))
                continue;

            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with {Y = -position.Y});

            // If beacon not on screen then ignore it.
            if (!area.Contains(localPos.Floored()))
                continue;

            var distance = (localPos - mousePos).Length();

            if (distance > BeaconSnapRange * UIScale ||
                distance > nearestValue)
            {
                continue;
            }

            foundLocalPos = localPos;
            nearestValue = distance;
            foundBeacon = beaconObj;
        }

        return foundBeacon != default;
    }

    /// <summary>
    /// Sets the map objects for the next draw.
    /// </summary>
    public void SetMapObjects(Dictionary<MapId, List<IMapObject>> mapObjects)
    {
        _mapObjects.Clear();

        if (mapObjects.TryGetValue(ViewingMap, out var obbies))
        {
            _mapObjects.AddRange(obbies);
        }
    }

    /// <summary>
    /// Draw the coordinate data with a custom color.
    /// </summary>
    protected void DrawData(DrawingHandleScreen handle, string text, Color color)
    {
        var margin = 5f;
        var font = _font;
        var dimensions = handle.GetDimensions(font, text, 1f);
        var position = new Vector2(margin, PixelHeight - dimensions.Y - margin);
        handle.DrawString(font, position, text, color);
    }
}
