using System;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.LifeInsurance;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Exodus.LifeInsurance.UI;

[GenerateTypedNameReferences]
public sealed partial class LifeInsuranceWindow : FancyWindow
{
    private static readonly Color Accent = Color.FromHex("#9573AF");
    private static readonly Color RowBackground = Color.FromHex("#241F30");

    public Action? OnRecordDna;
    public Action<Guid>? OnBuy;
    public Action<Guid>? OnDelete;

    public LifeInsuranceWindow()
    {
        RobustXamlLoader.Load(this);
        RecordButton.OnPressed += _ => OnRecordDna?.Invoke();
    }

    public void Populate(LifeInsuranceConsoleState state)
    {
        ScannerOccupantLabel.Text = state.ScannerOccupantName != null
            ? Loc.GetString("life-insurance-scanner-occupant", ("name", state.ScannerOccupantName))
            : Loc.GetString("life-insurance-scanner-empty");

        RecordButton.Disabled = !state.Scanner.Connected || state.ScannerOccupantName == null;

        ScannerStatusLabel.SetMarkup(FormatStatus("life-insurance-status-scanner", state.Scanner));
        ClonerStatusLabel.SetMarkup(FormatStatus("life-insurance-status-cloner", state.Cloner));

        RecordList.RemoveAllChildren();
        foreach (var record in state.Records)
        {
            RecordList.AddChild(BuildRow(record, state.MaxInsurances, state.Price));
        }
    }

    private Control BuildRow(LifeInsuranceRecordEntry record, int maxInsurances, int price)
    {
        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(6, 3, 6, 3)
        };

        inner.AddChild(new Label
        {
            Text = record.Name,
            HorizontalExpand = true
        });

        inner.AddChild(new Label
        {
            Text = $"{record.Insurances}/{maxInsurances}",
            Modulate = Accent,
            Margin = new Thickness(0, 0, 8, 0)
        });

        var buyButton = new Button
        {
            Text = Loc.GetString("life-insurance-buy-button", ("price", price)),
            Disabled = record.Insurances >= maxInsurances,
            Margin = new Thickness(0, 0, 4, 0)
        };
        var userId = record.UserId;
        buyButton.OnPressed += _ => OnBuy?.Invoke(userId);
        inner.AddChild(buyButton);

        var deleteButton = new Button
        {
            Text = Loc.GetString("life-insurance-delete-button"),
            StyleClasses = { "Caution" }
        };
        deleteButton.OnPressed += _ => OnDelete?.Invoke(userId);
        inner.AddChild(deleteButton);

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = RowBackground },
            Margin = new Thickness(0, 0, 0, 3),
            Children = { inner }
        };
    }

    private string FormatStatus(string nameLoc, LifeInsuranceMachineStatus status)
    {
        var name = Loc.GetString(nameLoc);
        if (!status.Connected)
            return Loc.GetString("life-insurance-status-disconnected", ("machine", name));

        if (status.Unpowered)
            return Loc.GetString("life-insurance-status-unpowered", ("machine", name));

        if (status.OnGridPower)
            return Loc.GetString("life-insurance-status-grid", ("machine", name));

        return Loc.GetString("life-insurance-status-battery", ("machine", name), ("percent", (int) MathF.Round(status.BatteryPercent * 100f)));
    }
}
