using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.LifeInsurance.UI;

[GenerateTypedNameReferences]
public sealed partial class LifeInsuranceWakeUpWindow : DefaultWindow
{
    public LifeInsuranceWakeUpWindow()
    {
        RobustXamlLoader.Load(this);
        NarrativeLabel.SetMarkup(Loc.GetString("life-insurance-wakeup-text"));
    }
}
