using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Silicons.StationAi.UI;

[GenerateTypedNameReferences]
public sealed partial class AiRenameWindow : FancyWindow
{
    public event Action<string>? OnConfirmed;

    private bool _confirmed;

    public AiRenameWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => TryConfirm();
        CancelButton.OnPressed += _ => Close();
        NameEdit.OnTextEntered += _ => TryConfirm();
    }

    public void SetCurrentName(string name)
    {
        NameEdit.Text = name;
    }

    public bool WasConfirmed => _confirmed;

    private void TryConfirm()
    {
        var name = NameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;

        _confirmed = true;
        OnConfirmed?.Invoke(name);
        Close();
    }
}
