- type: pointOfInterest
  parent: BaseMobilePOI
  id: BasePOI
  abstract: true
  addComponents:
  - type: ForceAnchor
  - type: Tag # Exodus
    tags: [ POI ]

# Mono

- type: pointOfInterest
  id: BaseMobilePOI
  abstract: true
  minimumDistance: 4000 # Exodus
  maximumDistance: 8000 # Exodus
  spawnGamePreset: [ NFAdventure, NFPirate, MonoStandard, MonoRogueTSF, MonoRogueUSSP, MonoTSFUSSP, MonoADS, MonoChimera, MonoMixed, MonoAllAtOnce ] # Behold my list of gamerules
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true

- type: pointOfInterest
  parent: BaseMobilePOI
  id: BaseRepairablePOI
  abstract: true
  addComponents:
  - type: InitRepairSnapshot
