[net]
tickrate = 30
log_late_msg = false
lidgren_log_warning = false
lidgren_log_error = false

[game]
hostname = "Exodus: Dev"
desc = "Сервер предназначенный для отдела разработки Exodus: закрытые тесты, публичные тесты. Элемент стабильности сборки."
lobbyduration = 360

[game.panic_bunker]
disable_with_admins = true
enable_without_admins = false
count_deadminned_admins = true
show_reason = true

[game.dynamic_roles]
enabled = false

[movement]
mob_pushing = false

[vote]
enabled = false
map_enabled = false
auto_map_vote = false

[atmos]
space_wind = true

[shuttle]
auto_call_time = 0
mass_limit = 0

[shuttle.impact]
minimum_velocity = 105

[viewport]
maximum_width = 30

[ooc]
show_ooc_patron_color = false
enable_during_round = false

[rules]
time = 30

[ic]
flavor_text = true

[surgery]
can_operate_on_self = false

[nf14.salvage]
expedition_rewards_enabled = true

[admin]
note_fresh_days = 0
allow_multi_server_play = false

[chat]
motd = "Добро пожаловать на Exodus!\n[REDACTED]\n\nВы находитесь в отделе разработки Exodus, за несанкционированный доступ проследует незамедлительное наказание."

[console]
loginlocal = true

[infolinks]
discord = "https://discord.gg/ss220"
wiki = "https://ex.ss220.club"
github = "https://github.com/SerbiaStrong-220/Monolith"
website = "https://serbiastrong-220.github.io/webmap-exodus"
