using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class SavingsWindow : FancyWindow
{
    /// <summary>
    /// Raised with the requested transfer amount. Positive moves main account -> savings,
    /// negative moves savings -> main account.
    /// </summary>
    public event Action<int>? OnTransfer;

    public SavingsWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("savings-window-title");

        ToSavingsButton.OnPressed += _ => Submit(1);
        ToAccountButton.OnPressed += _ => Submit(-1);

        // Only allow digits in the amount field (empty is allowed so it can be cleared).
        AmountEdit.IsValid = static text => text.All(static c => c is >= '0' and <= '9');
    }

    public void SetBalances(int account, long savings)
    {
        AccountLabel.Text = BankSystemExtensions.ToSpesoString(account);
        SavingsLabel.Text = BankSystemExtensions.ToSpesoString(savings);
    }

    private void Submit(int sign)
    {
        if (!long.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
            return;

        // Clamp to int range; the server clamps the actual move to the available balance,
        // so entering more than you have just transfers everything available.
        var clamped = (int)Math.Min(amount, int.MaxValue);
        OnTransfer?.Invoke(sign * clamped);
    }
}
