// Copyright Rane (elijahrane@gmail.com) 2025
// All rights reserved. Relicensed under AGPL with permission

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.FireControl;
using Content.Shared._Mono.ShipGuns;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics; // Exodus
using Content.Shared.Exodus.ShipShields; // Exodus
using Robust.Shared.Timing; // Exodus
using Content.Client._Exodus.FireControl; // Exodus
using Content.Shared.Weapons.Ranged.Components; // Exodus

namespace Content.Client._Mono.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    public FireControlNavControl Radar => NavRadar;
    public Action? OnServerRefresh;
    public Action? OnWeaponSelectionChanged;

    public readonly Dictionary<NetEntity, Button> WeaponsList = new();

    // Dictionary to store weapon name to entity mapping for easier filtering
    private readonly Dictionary<string, NetEntity> _weaponNameToEntity = new();

    // Dictionary to store weapon entity to type mapping
    private readonly Dictionary<NetEntity, ShipGunType> _weaponTypes = new();

    private FireControlConsoleBoundInterfaceState? _currentState;

    // Exodus-Start
    private const float UpdateTimer = 1f;
    private float _updateAccumulator;
    // Exodus-End

    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
        SelectAllButton.OnPressed += SelectAllWeapons;
        UnselectAllButton.OnPressed += UnselectAllWeapons;
        SelectBallisticButton.OnPressed += SelectBallisticWeapons;
        SelectEnergyButton.OnPressed += SelectEnergyWeapons;
        SelectMissileButton.OnPressed += SelectMissileWeapons;

        // Exodus: Shield status
        ShieldLoadBar.ForegroundStyleBoxOverride = new StyleBoxFlat()
        {
            BackgroundColor = Color.Red
        };
    }

    private void SelectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = true;
        }

        OnWeaponSelectionChanged?.Invoke();

        UpdateAllWeaponButtonTexts();
    }

    private void UnselectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        OnWeaponSelectionChanged?.Invoke();

        UpdateAllWeaponButtonTexts();
    }

    private void SelectBallisticWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only ballistic weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Ballistic)
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();
    }

    private void SelectEnergyWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only energy weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Energy)
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();
    }

    private void SelectMissileWeapons(BaseButton.ButtonEventArgs args)
    {
        // First unselect all weapons
        foreach (var button in WeaponsList.Values)
        {
            button.Pressed = false;
        }

        // Then select only missile weapons
        foreach (var kvp in WeaponsList)
        {
            var weaponEntity = kvp.Key;
            var button = kvp.Value;

            if (_weaponTypes.TryGetValue(weaponEntity, out var type) && type == ShipGunType.Missile)
            {
                button.Pressed = true;
            }
        }

        OnWeaponSelectionChanged?.Invoke();
        UpdateAllWeaponButtonTexts();
    }

    /// <summary>
    /// Updates the text of a weapon button based on its selection state and manual reload status.
    /// </summary>
    private void UpdateWeaponButtonText(Button button, FireControllableEntry controllable)
    {
        if (button.Pressed && controllable.HasManualReload && controllable.AmmoCount.HasValue)
        {
            button.Text = Loc.GetString("gunnery-gun-select-ammo", ("name", controllable.Name), ("ammo", controllable.AmmoCount.Value));

            if (controllable.AmmoCount.Value == 0)
            {
                button.ModulateSelfOverride = Color.Red;
            }
            else
            {
                button.ModulateSelfOverride = null;
            }
        }
        else
        {
            button.Text = Loc.GetString("gunnery-gun-select", ("name", controllable.Name));
            button.ModulateSelfOverride = null;
        }
    }

    /// <summary>
    /// Updates all weapon button texts based on current selection state.
    /// </summary>
    private void UpdateAllWeaponButtonTexts()
    {
        foreach (var (netEntity, button) in WeaponsList)
        {
            var controllable = _currentState?.FireControllables?.FirstOrDefault(c => c.NetEntity == netEntity);

            if (controllable.HasValue)
            {
                UpdateWeaponButtonText(button, controllable.Value);
            }
        }
    }

    public void UpdateStatus(FireControlConsoleBoundInterfaceState state)
    {
        _currentState = state;
        NavRadar.UpdateState(state.NavState);
        UpdateShieldState(state.ShieldState); // Exodus

        if (state.Connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            RefreshButton.Disabled = false;
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        UpdateWeaponsList(state);

        UpdateAllWeaponButtonTexts();

        // Update the category buttons state based on whether weapons of that type are available
        bool hasBallisticWeapons = false;
        bool hasEnergyWeapons = false;
        bool hasMissileWeapons = false;

        foreach (var kvp in _weaponTypes)
        {
            var type = kvp.Value;

            if (type == ShipGunType.Ballistic)
                hasBallisticWeapons = true;
            else if (type == ShipGunType.Energy)
                hasEnergyWeapons = true;
            else if (type == ShipGunType.Missile)
                hasMissileWeapons = true;

            if (hasBallisticWeapons && hasEnergyWeapons && hasMissileWeapons)
                break;
        }

        SelectBallisticButton.Disabled = !hasBallisticWeapons;
        SelectEnergyButton.Disabled = !hasEnergyWeapons;
        SelectMissileButton.Disabled = !hasMissileWeapons;
    }

    private void UpdateWeaponsList(FireControlConsoleBoundInterfaceState state)
    {
        if (state.FireControllables == null)
        {
            WeaponsList.Clear();
            ControllablesBox.DisposeAllChildren();
            _weaponNameToEntity.Clear();
            _weaponTypes.Clear();
            return;
        }

        var toRemove = new HashSet<NetEntity>(WeaponsList.Keys);
        _weaponNameToEntity.Clear();
        _weaponTypes.Clear();

        foreach (var controllable in state.FireControllables)
        {
            // Store the weapon name and entity for filtering
            _weaponNameToEntity[controllable.Name] = controllable.NetEntity;

            // Store the weapon type if available
            var entity = _entityManager.GetEntity(controllable.NetEntity);
            if (_entityManager.TryGetComponent<ShipGunTypeComponent>(entity, out var typeComp))
            {
                _weaponTypes[controllable.NetEntity] = typeComp.Type;
            }

            if (WeaponsList.TryGetValue(controllable.NetEntity, out var existingButton))
            {
                toRemove.Remove(controllable.NetEntity);
                UpdateWeaponButtonText(existingButton, controllable);
            }
            else
            {
                var button = new ReloadProgressButton // Exodus: reload progress overlay
                {
                    ToggleMode = true,
                    Text = controllable.Name,
                    StyleClasses = { "ButtonSquare OpenRight" },
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 1)
                };

                button.OnToggled += _ =>
                {
                    OnWeaponSelectionChanged?.Invoke();
                    UpdateAllWeaponButtonTexts();
                };

                ControllablesBox.AddChild(button);
                WeaponsList.Add(controllable.NetEntity, button);

                UpdateWeaponButtonText(button, controllable);
            }
        }

        foreach (var entity in toRemove)
        {
            if (WeaponsList.TryGetValue(entity, out var button))
            {
                ControllablesBox.RemoveChild(button);
                WeaponsList.Remove(entity);
            }
        }

        SelectAllButton.Disabled = WeaponsList.Count == 0;
        UnselectAllButton.Disabled = WeaponsList.Count == 0;
    }

    // Exodus-Start
    private void UpdateShieldState(ShipShieldState? state)
    {
        if (state is not { } shieldState)
        {
            ShieldContainer.Visible = false;
            return;
        }

        // update status
        if (shieldState.OverloadAccumulator > 0) // overloaded
        {
            ShieldStatus.Text = Loc.GetString("gunnery-shield-overload");
            ShieldStatus.FontColorOverride = Color.Red;
        }
        else if (shieldState.Draw == 0) // normal
        {
            ShieldStatus.Text = Loc.GetString("gunnery-shield-normal");
            ShieldStatus.FontColorOverride = Color.Green;
        }
        else // under load
        {
            ShieldStatus.Text = Loc.GetString("gunnery-shield-under-load");
            ShieldStatus.FontColorOverride = Color.Orange;
        }

        // load
        ShieldLoad.Text = Loc.GetString("gunnery-shield-load", ("draw", Math.Round(shieldState.BaseDraw + shieldState.Draw / 1000f, 1)));

        // recovery label
        ShieldRecoveryLabel.Visible = shieldState.OverloadAccumulator > 0;
        ShieldRecoveryLabel.Text = Loc.GetString("gunnery-shield-recovery-label", ("time", shieldState.OverloadAccumulator));

        // load bar
        ShieldLoadBar.Value = shieldState.BaseDraw + shieldState.Draw;
        ShieldLoadBar.MaxValue = shieldState.MaxDraw;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _updateAccumulator += args.DeltaSeconds;

        if (_updateAccumulator > UpdateTimer)
        {
            OnServerRefresh?.Invoke(); // a crutch, what can you make me?
            _updateAccumulator = 0;
        }

        UpdateReloadProgress();
    }

    private void UpdateReloadProgress()
    {
        if (_currentState?.FireControllables == null)
            return;

        foreach (var controllable in _currentState.FireControllables)
        {
            if (!WeaponsList.TryGetValue(controllable.NetEntity, out var button)
                || button is not ReloadProgressButton reloadButton
                || !reloadButton.Pressed)
                continue;

            reloadButton.NextFire =
                _entityManager.TryGetComponent<GunComponent>(_entityManager.GetEntity(controllable.NetEntity), out var gun)
                    ? gun.NextFire
                    : controllable.NextFire;
        }
    }
    // Exodus-End
}
