name: "Discord changelog"

on:
  pull_request_target:
    branches:
      - master
    types: [closed]

jobs:
  send_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Send changelog
    steps:
      - name: Generate and send message
        uses: SerbiaStrong-220/ss220-DiscordCLAct@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          pull_request_url: ${{ github.event.pull_request.url }}
          # changelog_replace_data: '{"add:": ":newspaper:", "remove:": ":scissors:", "tweak:": ":gear:", "fix:": ":tools:"}'
          # webhhok_embed_color: '#346EEB'
          # webhook_username: 'SS220 changelog'
          # webhook_avatar_url: 'https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/refs/heads/master/logo.png'
